--!strict

local ClassStageDefs = {
    knight = { id = 'knight', archetypeId = 'knight_path', stage = 'Base', displayName = 'Knight', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'melee_mastery_1', 'armor_training_1' } },
    high_knight = { id = 'high_knight', archetypeId = 'knight_path', stage = 'High', displayName = 'High Knight', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'melee_mastery_2', 'armor_training_2' } },
    knight_rebirthed = { id = 'knight_rebirthed', archetypeId = 'knight_path', stage = 'Rebirth', displayName = 'Knight (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_mastery', 'frontline_presence' } },
    lord_knight = { id = 'lord_knight', archetypeId = 'knight_path', stage = 'Advanced', displayName = 'Lord Knight', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'lordship_of_steel', 'battlefield_overrun' } },
    assassin = { id = 'assassin', archetypeId = 'assassin_path', stage = 'Base', displayName = 'Assassin', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'shadow_instinct_1', 'katar_flow_1' } },
    high_assassin = { id = 'high_assassin', archetypeId = 'assassin_path', stage = 'High', displayName = 'High Assassin', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'shadow_instinct_2', 'katar_flow_2' } },
    assassin_rebirthed = { id = 'assassin_rebirthed', archetypeId = 'assassin_path', stage = 'Rebirth', displayName = 'Assassin (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_shadowcraft', 'venom_preparation' } },
    assassin_cross = { id = 'assassin_cross', archetypeId = 'assassin_path', stage = 'Advanced', displayName = 'Assassin Cross', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'poison_sovereignty', 'cross_execution' } },
    archer = { id = 'archer', archetypeId = 'archer_path', stage = 'Base', displayName = 'Archer', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'bow_mastery_1', 'evasion_instinct_1' } },
    high_archer = { id = 'high_archer', archetypeId = 'archer_path', stage = 'High', displayName = 'High Archer', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'bow_mastery_2', 'evasion_instinct_2' } },
    archer_rebirthed = { id = 'archer_rebirthed', archetypeId = 'archer_path', stage = 'Rebirth', displayName = 'Archer (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_precision', 'hunter_focus' } },
    sniper = { id = 'sniper', archetypeId = 'archer_path', stage = 'Advanced', displayName = 'Sniper', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'deadeye_hunter', 'storm_volley_instinct' } },
    mage = { id = 'mage', archetypeId = 'mage_path', stage = 'Base', displayName = 'Mage', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'spell_focus_1', 'arcane_control_1' } },
    high_mage = { id = 'high_mage', archetypeId = 'mage_path', stage = 'High', displayName = 'High Mage', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'spell_focus_2', 'arcane_control_2' } },
    mage_rebirthed = { id = 'mage_rebirthed', archetypeId = 'mage_path', stage = 'Rebirth', displayName = 'Mage (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_arcana', 'mana_resonance' } },
    warlock = { id = 'warlock', archetypeId = 'mage_path', stage = 'Advanced', displayName = 'Warlock', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'cataclysm_channel', 'party_arcana_domain' } },
    zero = { id = 'zero', archetypeId = 'zero_path', stage = 'Base', displayName = 'Zero', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'combo_drive_1', 'spatial_tempo_1' } },
    high_zero = { id = 'high_zero', archetypeId = 'zero_path', stage = 'High', displayName = 'High Zero', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'combo_drive_2', 'spatial_tempo_2' } },
    zero_rebirthed = { id = 'zero_rebirthed', archetypeId = 'zero_path', stage = 'Rebirth', displayName = 'Zero (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_afterimage', 'temporal_precision' } },
    transcendent_zero = { id = 'transcendent_zero', archetypeId = 'zero_path', stage = 'Advanced', displayName = 'Transcendent Zero', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'transcendent_combo_drive', 'paradox_finish' } },
    valkyrie = { id = 'valkyrie', archetypeId = 'valkyrie_path', stage = 'Base', displayName = 'Valkyrie', promotionLevel = 30, statPointBonusPerLevel = 3, skillPointBonusPerLevel = 1, passiveHooks = { 'aerial_mastery_1', 'wind_affinity_1' } },
    high_valkyrie = { id = 'high_valkyrie', archetypeId = 'valkyrie_path', stage = 'High', displayName = 'High Valkyrie', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'aerial_mastery_2', 'wind_affinity_2' } },
    valkyrie_rebirthed = { id = 'valkyrie_rebirthed', archetypeId = 'valkyrie_path', stage = 'Rebirth', displayName = 'Valkyrie (Rebirthed)', promotionLevel = 20, statPointBonusPerLevel = 4, skillPointBonusPerLevel = 1, passiveHooks = { 'rebirth_wings', 'storm_attunement' } },
    seraphim = { id = 'seraphim', archetypeId = 'valkyrie_path', stage = 'Advanced', displayName = 'Seraphim', promotionLevel = 40, statPointBonusPerLevel = 5, skillPointBonusPerLevel = 1, passiveHooks = { 'divine_sovereignty', 'heavens_descent' } },
}

return ClassStageDefs
