--!strict

return {
    power_slash = {
        id = 'power_slash',
        displayName = 'Power Slash',
        description = 'A wide cleave that punches through multiple enemies.',
        toolKind = 'skill',
        cooldown = 2.75,
        range = 18,
        width = 11,
        damage = 34,
        iconColor = Color3.fromRGB(116, 214, 255),
    },
    arc_flare = {
        id = 'arc_flare',
        displayName = 'Arc Flare',
        description = 'Launch a sweeping neon arc that tears through enemies in front of you.',
        toolKind = 'skill',
        cooldown = 3.25,
        range = 20,
        width = 9,
        damage = 42,
        maxTargets = 4,
        iconColor = Color3.fromRGB(121, 238, 255),
    },
    nova_strike = {
        id = 'nova_strike',
        displayName = 'Nova Strike',
        description = 'Fire a focused spear of energy with high single-target pressure.',
        toolKind = 'skill',
        cooldown = 4.5,
        range = 28,
        width = 5,
        damage = 58,
        maxTargets = 2,
        iconColor = Color3.fromRGB(168, 203, 255),
    },
    vortex_spin = {
        id = 'vortex_spin',
        displayName = 'Vortex Spin',
        description = 'Spin up a close-range vortex that hits all nearby foes.',
        toolKind = 'skill',
        cooldown = 6,
        range = 14,
        width = 14,
        damage = 38,
        maxTargets = 8,
        iconColor = Color3.fromRGB(192, 138, 255),
    },
    comet_drop = {
        id = 'comet_drop',
        displayName = 'Comet Drop',
        description = 'Call down an explosive comet blast around your position.',
        toolKind = 'skill',
        cooldown = 7.25,
        range = 16,
        width = 16,
        damage = 52,
        maxTargets = 10,
        iconColor = Color3.fromRGB(255, 174, 112),
    },
    razor_orbit = {
        id = 'razor_orbit',
        displayName = 'Razor Orbit',
        description = 'Orbiting blades burst outward and carve a wide frontal zone.',
        toolKind = 'skill',
        cooldown = 5.4,
        range = 22,
        width = 12,
        damage = 46,
        maxTargets = 6,
        iconColor = Color3.fromRGB(206, 246, 255),
    },
}
