--!strict

return {
    power_slash = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'PowerSlash',
                vfx = {
                    mode = 'charge',
                    duration = 0.12,
                    width = 8,
                    range = 8,
                },
            },
            {
                marker = 'Slash1',
                t = 0.14,
                effect = 'PowerSlash',
                vfx = {
                    mode = 'sweep',
                    duration = 0.26,
                    width = 12,
                    range = 18,
                    arc = 3.6,
                    side = 1,
                    spin = 1.1,
                },
                hitbox = {
                    shape = 'cone',
                    range = 18,
                    dotThreshold = 0.2,
                    maxTargets = 3,
                    damageScale = 1,
                },
            },
            {
                marker = 'Recover',
                t = 0.34,
                effect = 'PowerSlash',
                vfx = {
                    mode = 'dissipate',
                    duration = 0.16,
                    width = 9,
                    range = 10,
                },
            },
        },
    },
    arc_flare = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'ArcFlare',
                vfx = {
                    mode = 'charge',
                    duration = 0.14,
                    width = 7,
                    range = 7,
                },
            },
            {
                marker = 'Slash1',
                t = 0.16,
                effect = 'ArcFlare',
                vfx = {
                    mode = 'sweep',
                    duration = 0.26,
                    width = 8,
                    range = 12,
                    arc = 4.2,
                    side = 1,
                    spin = 1.25,
                },
                hitbox = {
                    shape = 'cone',
                    range = 12,
                    dotThreshold = 0.15,
                    maxTargets = 3,
                    damageScale = 0.58,
                },
            },
            {
                marker = 'Slash2',
                t = 0.34,
                effect = 'ArcFlare',
                vfx = {
                    mode = 'sweep',
                    duration = 0.3,
                    width = 10,
                    range = 20,
                    arc = 5.2,
                    side = -1,
                    spin = 1.35,
                },
                hitbox = {
                    shape = 'cone',
                    range = 20,
                    dotThreshold = 0.3,
                    maxTargets = 4,
                    damageScale = 0.42,
                },
            },
            {
                marker = 'Recover',
                t = 0.58,
                effect = 'ArcFlare',
                vfx = {
                    mode = 'dissipate',
                    duration = 0.18,
                    width = 8,
                    range = 10,
                },
            },
        },
    },
    nova_strike = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'NovaStrike',
                vfx = {
                    mode = 'charge',
                    duration = 0.1,
                    width = 5,
                    range = 5,
                },
            },
            {
                marker = 'Dash',
                t = 0.12,
                move = {
                    type = 'dash',
                    distance = 4,
                },
                effect = 'NovaStrike',
                vfx = {
                    mode = 'dash',
                    duration = 0.12,
                    width = 5,
                    range = 8,
                },
            },
            {
                marker = 'Slash1',
                t = 0.22,
                effect = 'NovaStrike',
                vfx = {
                    mode = 'projectile',
                    duration = 0.24,
                    width = 4,
                    range = 28,
                    spin = 2.1,
                },
                hitbox = {
                    shape = 'cone',
                    range = 28,
                    dotThreshold = 0.72,
                    maxTargets = 2,
                    damageScale = 1,
                },
            },
            {
                marker = 'Recover',
                t = 0.46,
                effect = 'NovaStrike',
                vfx = {
                    mode = 'impact',
                    duration = 0.2,
                    width = 7,
                    range = 8,
                },
            },
        },
    },
    vortex_spin = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'VortexSpin',
                vfx = {
                    mode = 'charge',
                    duration = 0.14,
                    width = 10,
                    range = 8,
                },
            },
            {
                marker = 'Slash1',
                t = 0.18,
                effect = 'VortexSpin',
                vfx = {
                    mode = 'orbit',
                    duration = 0.28,
                    width = 10,
                    range = 10,
                    radius = 5,
                    turns = 1.4,
                },
                hitbox = {
                    shape = 'radial',
                    range = 10,
                    maxTargets = 6,
                    damageScale = 0.56,
                },
            },
            {
                marker = 'Slash2',
                t = 0.4,
                effect = 'VortexSpin',
                vfx = {
                    mode = 'orbit_burst',
                    duration = 0.32,
                    width = 13,
                    range = 14,
                    radius = 7,
                    turns = 2.25,
                },
                hitbox = {
                    shape = 'radial',
                    range = 14,
                    maxTargets = 8,
                    damageScale = 0.44,
                },
            },
        },
    },
    comet_drop = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'CometDrop',
                vfx = {
                    mode = 'charge',
                    duration = 0.16,
                    width = 10,
                    range = 10,
                },
            },
            {
                marker = 'Slash1',
                t = 0.24,
                effect = 'CometDrop',
                vfx = {
                    mode = 'drop',
                    duration = 0.24,
                    width = 10,
                    range = 12,
                    height = 24,
                },
                hitbox = {
                    shape = 'radial',
                    range = 10,
                    maxTargets = 8,
                    damageScale = 0.7,
                },
            },
            {
                marker = 'Slash2',
                t = 0.42,
                effect = 'CometDrop',
                vfx = {
                    mode = 'impact',
                    duration = 0.26,
                    width = 16,
                    range = 16,
                },
                hitbox = {
                    shape = 'radial',
                    range = 16,
                    maxTargets = 10,
                    damageScale = 0.3,
                    allowRepeat = true,
                },
            },
        },
    },
    razor_orbit = {
        phases = {
            {
                marker = 'Windup',
                t = 0.0,
                effect = 'RazorOrbit',
                vfx = {
                    mode = 'orbit',
                    duration = 0.18,
                    width = 8,
                    range = 8,
                    radius = 4,
                    turns = 1,
                },
            },
            {
                marker = 'Slash1',
                t = 0.2,
                effect = 'RazorOrbit',
                vfx = {
                    mode = 'orbit_dash',
                    duration = 0.24,
                    width = 10,
                    range = 14,
                    radius = 5,
                    turns = 1.8,
                },
                hitbox = {
                    shape = 'cone',
                    range = 14,
                    dotThreshold = 0.04,
                    maxTargets = 4,
                    damageScale = 0.56,
                },
            },
            {
                marker = 'Slash2',
                t = 0.38,
                effect = 'RazorOrbit',
                vfx = {
                    mode = 'sweep',
                    duration = 0.26,
                    width = 12,
                    range = 22,
                    arc = 4.8,
                    side = 1,
                    spin = 1.4,
                },
                hitbox = {
                    shape = 'cone',
                    range = 22,
                    dotThreshold = 0.02,
                    maxTargets = 6,
                    damageScale = 0.44,
                },
            },
            {
                marker = 'Recover',
                t = 0.58,
                effect = 'RazorOrbit',
                vfx = {
                    mode = 'dissipate',
                    duration = 0.14,
                    width = 9,
                    range = 9,
                },
            },
        },
    },
}
