--!strict

return {
    knight_training_blade = {
        id = 'knight_training_blade',
        displayName = 'Knight Training Blade',
        description = 'A simple knight sword built for the clean reboot slice.',
        toolKind = 'weapon',
        range = 10,
        damageMin = 12,
        damageMax = 16,
        swingCooldown = 0.55,
        handleColor = Color3.fromRGB(196, 205, 214),
        accentColor = Color3.fromRGB(78, 138, 255),
    },
    deku_combat_emblem = {
        id = 'deku_combat_emblem',
        displayName = 'Deku Combat Emblem',
        description = 'Equip this to use the older Deku combat animation style.',
        toolKind = 'style',
        rarity = 'rare',
        stackable = false,
        animationStyleOverride = 'DekuLegacy',
        allowsCombatStyleOnly = true,
        handleColor = Color3.fromRGB(72, 132, 86),
        accentColor = Color3.fromRGB(214, 255, 223),
    },
    deku_skin = {
        id = 'deku_skin',
        displayName = 'Deku Skin',
        description = 'Apply the Deku look to your current character.',
        toolKind = 'skin',
        rarity = 'rare',
        stackable = false,
        skinTemplateId = 'DekuCharacterTemplate',
        handleColor = Color3.fromRGB(72, 132, 86),
        accentColor = Color3.fromRGB(214, 255, 223),
    },
    gojo_white_skin = {
        id = 'gojo_white_skin',
        displayName = 'Gojo White',
        description = 'Apply the Gojo White look to your current character.',
        toolKind = 'skin',
        rarity = 'epic',
        stackable = false,
        skinTemplateId = 'GojoWhiteCharacterTemplate',
        skinAssetId = 91131914057854,
        handleColor = Color3.fromRGB(211, 219, 233),
        accentColor = Color3.fromRGB(244, 249, 255),
    },
    luffy_skin = {
        id = 'luffy_skin',
        displayName = 'Luffy',
        description = 'Apply the Luffy look to your current character.',
        toolKind = 'skin',
        rarity = 'epic',
        stackable = false,
        skinTemplateId = 'LuffyCharacterTemplate',
        skinAssetId = 9465786796,
        handleColor = Color3.fromRGB(227, 88, 78),
        accentColor = Color3.fromRGB(255, 214, 123),
    },
    luffy_gear_5_skin = {
        id = 'luffy_gear_5_skin',
        displayName = 'Luffy Gear 5',
        description = 'Apply the Luffy Gear 5 look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'LuffyGear5CharacterTemplate',
        skinAssetId = 10039008438,
        handleColor = Color3.fromRGB(235, 240, 255),
        accentColor = Color3.fromRGB(255, 255, 255),
    },
    sukuna_skin = {
        id = 'sukuna_skin',
        displayName = 'Sukuna',
        description = 'Apply the Sukuna look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'SukunaCharacterTemplate',
        skinAssetId = 136031016368713,
        handleColor = Color3.fromRGB(178, 74, 112),
        accentColor = Color3.fromRGB(255, 201, 227),
    },
    deku_one_for_all_skin = {
        id = 'deku_one_for_all_skin',
        displayName = 'Deku One For All',
        description = 'Apply the Deku One For All look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'DekuOneForAllCharacterTemplate',
        skinAssetId = 6452399145,
        handleColor = Color3.fromRGB(66, 154, 96),
        accentColor = Color3.fromRGB(211, 255, 227),
    },
    susanoo_sasuke_skin = {
        id = 'susanoo_sasuke_skin',
        displayName = 'Susanoo Sasuke',
        description = 'Apply the Susanoo Sasuke look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'SusanooSasukeCharacterTemplate',
        skinAssetId = 8254559912,
        handleColor = Color3.fromRGB(109, 89, 219),
        accentColor = Color3.fromRGB(211, 201, 255),
    },
    kusanagi_skin = {
        id = 'kusanagi_skin',
        displayName = 'Kusanagi',
        description = 'Apply the Kusanagi look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'KusanagiCharacterTemplate',
        skinAssetId = 289122902,
        handleColor = Color3.fromRGB(132, 118, 206),
        accentColor = Color3.fromRGB(221, 214, 255),
    },
    werewolf_magic_skin = {
        id = 'werewolf_magic_skin',
        displayName = 'Werewolf Magic',
        description = 'Apply the Werewolf Magic look to your current character.',
        toolKind = 'skin',
        rarity = 'epic',
        stackable = false,
        skinTemplateId = 'WerewolfMagicCharacterTemplate',
        skinAssetId = 1112719593,
        handleColor = Color3.fromRGB(146, 108, 186),
        accentColor = Color3.fromRGB(238, 220, 255),
    },
    imported_chaos_edge = {
        id = 'imported_chaos_edge',
        displayName = 'Chaos Edge',
        description = 'Raw imported marketplace sword with its original scripts and keybinds intact.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288487412,
        handleColor = Color3.fromRGB(132, 68, 48),
        accentColor = Color3.fromRGB(255, 145, 84),
    },
    imported_azure_sword = {
        id = 'imported_azure_sword',
        displayName = 'Azure Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288498712,
        handleColor = Color3.fromRGB(84, 148, 255),
        accentColor = Color3.fromRGB(205, 231, 255),
    },
    imported_crimson_catseye_crescendo_sword = {
        id = 'imported_crimson_catseye_crescendo_sword',
        displayName = 'Crimson Catseye Crescendo Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288419155,
        handleColor = Color3.fromRGB(223, 87, 117),
        accentColor = Color3.fromRGB(255, 211, 219),
    },
    imported_overseer_crescendo_sword = {
        id = 'imported_overseer_crescendo_sword',
        displayName = 'Overseer Crescendo Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288721851,
        handleColor = Color3.fromRGB(136, 175, 244),
        accentColor = Color3.fromRGB(218, 233, 255),
    },
    imported_shadow_crescendo_sword = {
        id = 'imported_shadow_crescendo_sword',
        displayName = 'Shadow Crescendo Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288446354,
        handleColor = Color3.fromRGB(86, 79, 111),
        accentColor = Color3.fromRGB(206, 198, 242),
    },
    imported_blue_crescendo_sword = {
        id = 'imported_blue_crescendo_sword',
        displayName = 'Blue Crescendo Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288311929,
        handleColor = Color3.fromRGB(96, 148, 249),
        accentColor = Color3.fromRGB(214, 232, 255),
    },
    imported_blade_ball_sword = {
        id = 'imported_blade_ball_sword',
        displayName = 'Blade Ball Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 15655452464,
        handleColor = Color3.fromRGB(121, 194, 255),
        accentColor = Color3.fromRGB(225, 245, 255),
    },
    imported_home_run_bat = {
        id = 'imported_home_run_bat',
        displayName = 'Home Run Bat',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10297935721,
        handleColor = Color3.fromRGB(197, 145, 96),
        accentColor = Color3.fromRGB(255, 230, 202),
    },
    imported_harbinger_scroll = {
        id = 'imported_harbinger_scroll',
        displayName = 'Harbinger Scroll Of Sevenless',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'mythic',
        stackable = false,
        importedAssetId = 10218426636,
        handleColor = Color3.fromRGB(108, 66, 154),
        accentColor = Color3.fromRGB(231, 207, 255),
    },
    imported_admin_sword_giver = {
        id = 'imported_admin_sword_giver',
        displayName = 'Admin Sword Giver',
        description = 'Marketplace admin sword package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'mythic',
        stackable = false,
        importedAssetId = 138162738042222,
        handleColor = Color3.fromRGB(255, 214, 120),
        accentColor = Color3.fromRGB(255, 241, 192),
    },
    imported_silent_pain = {
        id = 'imported_silent_pain',
        displayName = 'Silent Pain Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 425478761,
        handleColor = Color3.fromRGB(126, 98, 176),
        accentColor = Color3.fromRGB(224, 211, 255),
    },
    imported_celestial_glaive = {
        id = 'imported_celestial_glaive',
        displayName = 'Celestial Glaive 2.1',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'mythic',
        stackable = false,
        importedAssetId = 401624521,
        handleColor = Color3.fromRGB(121, 212, 255),
        accentColor = Color3.fromRGB(230, 248, 255),
    },
    imported_rb_dragon_sword = {
        id = 'imported_rb_dragon_sword',
        displayName = 'R&B Dragon Sword',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 146936491,
        handleColor = Color3.fromRGB(255, 126, 126),
        accentColor = Color3.fromRGB(222, 222, 255),
    },
    imported_sword_of_heartsongs = {
        id = 'imported_sword_of_heartsongs',
        displayName = 'Sword of Heartsongs',
        description = 'Marketplace weapon package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 8432488495,
        handleColor = Color3.fromRGB(255, 158, 212),
        accentColor = Color3.fromRGB(255, 225, 243),
    },
    imported_npc_blood_script = {
        id = 'imported_npc_blood_script',
        displayName = 'NPC Blood Effect Script',
        description = 'Marketplace script package preserved with original scripts.',
        toolKind = 'imported_tool',
        rarity = 'rare',
        stackable = false,
        importedAssetId = 136384701757787,
        handleColor = Color3.fromRGB(179, 64, 78),
        accentColor = Color3.fromRGB(255, 212, 218),
    },
    minor_healing_potion = {
        id = 'minor_healing_potion',
        displayName = 'Minor Healing Potion',
        description = 'Restores a small amount of HP.',
        toolKind = 'consumable',
        rarity = 'uncommon',
        healAmount = 45,
        stackable = true,
        handleColor = Color3.fromRGB(201, 42, 68),
        accentColor = Color3.fromRGB(255, 204, 204),
    },
    poring_jelly = {
        id = 'poring_jelly',
        displayName = 'Poring Jelly',
        description = 'A springy blob of slime jelly.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(255, 188, 220),
        accentColor = Color3.fromRGB(255, 230, 241),
    },
    green_slime_essence = {
        id = 'green_slime_essence',
        displayName = 'Green Slime Essence',
        description = 'A soft green residue from a field slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(109, 215, 129),
        accentColor = Color3.fromRGB(191, 255, 203),
    },
    blue_slime_essence = {
        id = 'blue_slime_essence',
        displayName = 'Blue Slime Essence',
        description = 'A cool residue from a blue slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(98, 171, 255),
        accentColor = Color3.fromRGB(201, 231, 255),
    },
    red_slime_essence = {
        id = 'red_slime_essence',
        displayName = 'Red Slime Essence',
        description = 'A hot residue from a red slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(255, 108, 122),
        accentColor = Color3.fromRGB(255, 207, 213),
    },
    slime_membrane = {
        id = 'slime_membrane',
        displayName = 'Slime Membrane',
        description = 'A gelatinous membrane peeled from a slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(231, 244, 255),
        accentColor = Color3.fromRGB(255, 255, 255),
    },
    slime_core = {
        id = 'slime_core',
        displayName = 'Slime Core',
        description = 'A condensed core from an evolved slime.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(184, 212, 255),
        accentColor = Color3.fromRGB(247, 251, 255),
    },
    frostfang_pelt = {
        id = 'frostfang_pelt',
        displayName = 'Frostfang Pelt',
        description = 'A chilled pelt taken from an IceMoon beast.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(160, 220, 255),
        accentColor = Color3.fromRGB(227, 248, 255),
    },
    moonpetal_bloom = {
        id = 'moonpetal_bloom',
        displayName = 'Moonpetal Bloom',
        description = 'A pale bloom with cold lunar energy.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(194, 243, 216),
        accentColor = Color3.fromRGB(236, 255, 244),
    },
    shardhorn_fragment = {
        id = 'shardhorn_fragment',
        displayName = 'Shardhorn Fragment',
        description = 'A splintered crystal horn shard.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(149, 224, 255),
        accentColor = Color3.fromRGB(225, 248, 255),
    },
    glacial_core = {
        id = 'glacial_core',
        displayName = 'Glacial Core',
        description = 'A frozen core pulsing with IceMoon energy.',
        toolKind = 'material',
        rarity = 'rare',
        stackable = true,
        handleColor = Color3.fromRGB(139, 240, 255),
        accentColor = Color3.fromRGB(235, 252, 255),
    },
    lunar_pollen = {
        id = 'lunar_pollen',
        displayName = 'Lunar Pollen',
        description = 'Glittering pollen shaken free from Moonpetal growths.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(227, 246, 202),
        accentColor = Color3.fromRGB(249, 255, 232),
    },
    frozen_talon = {
        id = 'frozen_talon',
        displayName = 'Frozen Talon',
        description = 'A sharp talon preserved by IceMoon frost.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(184, 234, 255),
        accentColor = Color3.fromRGB(243, 252, 255),
    },
    crystal_fleece = {
        id = 'crystal_fleece',
        displayName = 'Crystal Fleece',
        description = 'A shimmering tuft from a shardhorn grazer.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(180, 232, 255),
        accentColor = Color3.fromRGB(242, 250, 255),
    },
    giant_poring_card = {
        id = 'giant_poring_card',
        displayName = 'Giant Poring Card',
        description = 'A rare card etched with the Giant Poring.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(255, 170, 220),
        accentColor = Color3.fromRGB(255, 232, 244),
    },
    field_slime_green_card = {
        id = 'field_slime_green_card',
        displayName = 'Green Slime Card',
        description = 'A rare card etched with a Green Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(130, 223, 141),
        accentColor = Color3.fromRGB(230, 255, 230),
    },
    field_slime_blue_card = {
        id = 'field_slime_blue_card',
        displayName = 'Blue Slime Card',
        description = 'A rare card etched with a Blue Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(111, 180, 255),
        accentColor = Color3.fromRGB(228, 241, 255),
    },
    field_slime_red_card = {
        id = 'field_slime_red_card',
        displayName = 'Red Slime Card',
        description = 'A rare card etched with a Red Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(255, 128, 146),
        accentColor = Color3.fromRGB(255, 228, 232),
    },
    icemoon_frostfang_card = {
        id = 'icemoon_frostfang_card',
        displayName = 'Frostfang Lupus Card',
        description = 'A rare card etched with a Frostfang Lupus.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(176, 228, 255),
        accentColor = Color3.fromRGB(237, 250, 255),
    },
    icemoon_moonpetal_card = {
        id = 'icemoon_moonpetal_card',
        displayName = 'Moonpetal Stalker Card',
        description = 'A rare card etched with a Moonpetal Stalker.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(196, 244, 220),
        accentColor = Color3.fromRGB(241, 255, 246),
    },
    icemoon_shardhorn_card = {
        id = 'icemoon_shardhorn_card',
        displayName = 'Shardhorn Grazer Card',
        description = 'A rare card etched with a Shardhorn Grazer.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(168, 228, 255),
        accentColor = Color3.fromRGB(239, 252, 255),
    },
    icemoon_cryoshade_card = {
        id = 'icemoon_cryoshade_card',
        displayName = 'Cryoshade Fenrir Card',
        description = 'A rare card etched with Cryoshade Fenrir.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(149, 236, 255),
        accentColor = Color3.fromRGB(235, 252, 255),
    },
}
