--!strict

return {
    knight_training_blade = {
        id = 'knight_training_blade',
        displayName = 'Knight Training Blade',
        description = 'A simple knight sword built for the clean reboot slice.',
        toolKind = 'weapon',
        range = 10,
        damageMin = 12,
        damageMax = 16,
        swingCooldown = 0.55,
        handleColor = Color3.fromRGB(196, 205, 214),
        accentColor = Color3.fromRGB(78, 138, 255),
    },
    deku_combat_emblem = {
        id = 'deku_combat_emblem',
        displayName = 'Deku Combat Emblem',
        description = 'Equip this to use the older Deku combat animation style.',
        toolKind = 'style',
        rarity = 'rare',
        stackable = false,
        animationStyleOverride = 'DekuLegacy',
        allowsCombatStyleOnly = true,
        handleColor = Color3.fromRGB(72, 132, 86),
        accentColor = Color3.fromRGB(214, 255, 223),
    },
    deku_skin = {
        id = 'deku_skin',
        displayName = 'Deku Skin',
        description = 'Apply the Deku look to your current character.',
        toolKind = 'skin',
        rarity = 'rare',
        stackable = false,
        skinTemplateId = 'DekuCharacterTemplate',
        handleColor = Color3.fromRGB(72, 132, 86),
        accentColor = Color3.fromRGB(214, 255, 223),
    },
    gojo_white_skin = {
        id = 'gojo_white_skin',
        displayName = 'Gojo White',
        description = 'Apply the Gojo White look to your current character.',
        toolKind = 'skin',
        rarity = 'epic',
        stackable = false,
        skinTemplateId = 'GojoWhiteCharacterTemplate',
        skinAssetId = 91131914057854,
        handleColor = Color3.fromRGB(211, 219, 233),
        accentColor = Color3.fromRGB(244, 249, 255),
    },
    luffy_skin = {
        id = 'luffy_skin',
        displayName = 'Luffy',
        description = 'Apply the Luffy look to your current character.',
        toolKind = 'skin',
        rarity = 'epic',
        stackable = false,
        skinTemplateId = 'LuffyCharacterTemplate',
        skinAssetId = 9465786796,
        handleColor = Color3.fromRGB(227, 88, 78),
        accentColor = Color3.fromRGB(255, 214, 123),
    },
    luffy_gear_5_skin = {
        id = 'luffy_gear_5_skin',
        displayName = 'Luffy Gear 5',
        description = 'Apply the Luffy Gear 5 look to your current character.',
        toolKind = 'skin',
        rarity = 'mythic',
        stackable = false,
        skinTemplateId = 'LuffyGear5CharacterTemplate',
        skinAssetId = 10039008438,
        handleColor = Color3.fromRGB(235, 240, 255),
        accentColor = Color3.fromRGB(255, 255, 255),
    },
    imported_chaos_edge = {
        id = 'imported_chaos_edge',
        displayName = 'Chaos Edge',
        description = 'Raw imported marketplace sword with its original scripts and keybinds intact.',
        toolKind = 'imported_tool',
        rarity = 'epic',
        stackable = false,
        importedAssetId = 10288487412,
        handleColor = Color3.fromRGB(132, 68, 48),
        accentColor = Color3.fromRGB(255, 145, 84),
    },
    minor_healing_potion = {
        id = 'minor_healing_potion',
        displayName = 'Minor Healing Potion',
        description = 'Restores a small amount of HP.',
        toolKind = 'consumable',
        rarity = 'uncommon',
        healAmount = 45,
        stackable = true,
        handleColor = Color3.fromRGB(201, 42, 68),
        accentColor = Color3.fromRGB(255, 204, 204),
    },
    poring_jelly = {
        id = 'poring_jelly',
        displayName = 'Poring Jelly',
        description = 'A springy blob of slime jelly.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(255, 188, 220),
        accentColor = Color3.fromRGB(255, 230, 241),
    },
    green_slime_essence = {
        id = 'green_slime_essence',
        displayName = 'Green Slime Essence',
        description = 'A soft green residue from a field slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(109, 215, 129),
        accentColor = Color3.fromRGB(191, 255, 203),
    },
    blue_slime_essence = {
        id = 'blue_slime_essence',
        displayName = 'Blue Slime Essence',
        description = 'A cool residue from a blue slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(98, 171, 255),
        accentColor = Color3.fromRGB(201, 231, 255),
    },
    red_slime_essence = {
        id = 'red_slime_essence',
        displayName = 'Red Slime Essence',
        description = 'A hot residue from a red slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(255, 108, 122),
        accentColor = Color3.fromRGB(255, 207, 213),
    },
    slime_membrane = {
        id = 'slime_membrane',
        displayName = 'Slime Membrane',
        description = 'A gelatinous membrane peeled from a slime.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(231, 244, 255),
        accentColor = Color3.fromRGB(255, 255, 255),
    },
    slime_core = {
        id = 'slime_core',
        displayName = 'Slime Core',
        description = 'A condensed core from an evolved slime.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(184, 212, 255),
        accentColor = Color3.fromRGB(247, 251, 255),
    },
    frostfang_pelt = {
        id = 'frostfang_pelt',
        displayName = 'Frostfang Pelt',
        description = 'A chilled pelt taken from an IceMoon beast.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(160, 220, 255),
        accentColor = Color3.fromRGB(227, 248, 255),
    },
    moonpetal_bloom = {
        id = 'moonpetal_bloom',
        displayName = 'Moonpetal Bloom',
        description = 'A pale bloom with cold lunar energy.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(194, 243, 216),
        accentColor = Color3.fromRGB(236, 255, 244),
    },
    shardhorn_fragment = {
        id = 'shardhorn_fragment',
        displayName = 'Shardhorn Fragment',
        description = 'A splintered crystal horn shard.',
        toolKind = 'material',
        rarity = 'common',
        stackable = true,
        handleColor = Color3.fromRGB(149, 224, 255),
        accentColor = Color3.fromRGB(225, 248, 255),
    },
    glacial_core = {
        id = 'glacial_core',
        displayName = 'Glacial Core',
        description = 'A frozen core pulsing with IceMoon energy.',
        toolKind = 'material',
        rarity = 'rare',
        stackable = true,
        handleColor = Color3.fromRGB(139, 240, 255),
        accentColor = Color3.fromRGB(235, 252, 255),
    },
    lunar_pollen = {
        id = 'lunar_pollen',
        displayName = 'Lunar Pollen',
        description = 'Glittering pollen shaken free from Moonpetal growths.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(227, 246, 202),
        accentColor = Color3.fromRGB(249, 255, 232),
    },
    frozen_talon = {
        id = 'frozen_talon',
        displayName = 'Frozen Talon',
        description = 'A sharp talon preserved by IceMoon frost.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(184, 234, 255),
        accentColor = Color3.fromRGB(243, 252, 255),
    },
    crystal_fleece = {
        id = 'crystal_fleece',
        displayName = 'Crystal Fleece',
        description = 'A shimmering tuft from a shardhorn grazer.',
        toolKind = 'material',
        rarity = 'uncommon',
        stackable = true,
        handleColor = Color3.fromRGB(180, 232, 255),
        accentColor = Color3.fromRGB(242, 250, 255),
    },
    giant_poring_card = {
        id = 'giant_poring_card',
        displayName = 'Giant Poring Card',
        description = 'A rare card etched with the Giant Poring.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(255, 170, 220),
        accentColor = Color3.fromRGB(255, 232, 244),
    },
    field_slime_green_card = {
        id = 'field_slime_green_card',
        displayName = 'Green Slime Card',
        description = 'A rare card etched with a Green Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(130, 223, 141),
        accentColor = Color3.fromRGB(230, 255, 230),
    },
    field_slime_blue_card = {
        id = 'field_slime_blue_card',
        displayName = 'Blue Slime Card',
        description = 'A rare card etched with a Blue Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(111, 180, 255),
        accentColor = Color3.fromRGB(228, 241, 255),
    },
    field_slime_red_card = {
        id = 'field_slime_red_card',
        displayName = 'Red Slime Card',
        description = 'A rare card etched with a Red Slime.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(255, 128, 146),
        accentColor = Color3.fromRGB(255, 228, 232),
    },
    icemoon_frostfang_card = {
        id = 'icemoon_frostfang_card',
        displayName = 'Frostfang Lupus Card',
        description = 'A rare card etched with a Frostfang Lupus.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(176, 228, 255),
        accentColor = Color3.fromRGB(237, 250, 255),
    },
    icemoon_moonpetal_card = {
        id = 'icemoon_moonpetal_card',
        displayName = 'Moonpetal Stalker Card',
        description = 'A rare card etched with a Moonpetal Stalker.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(196, 244, 220),
        accentColor = Color3.fromRGB(241, 255, 246),
    },
    icemoon_shardhorn_card = {
        id = 'icemoon_shardhorn_card',
        displayName = 'Shardhorn Grazer Card',
        description = 'A rare card etched with a Shardhorn Grazer.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(168, 228, 255),
        accentColor = Color3.fromRGB(239, 252, 255),
    },
    icemoon_cryoshade_card = {
        id = 'icemoon_cryoshade_card',
        displayName = 'Cryoshade Fenrir Card',
        description = 'A rare card etched with Cryoshade Fenrir.',
        toolKind = 'card',
        rarity = 'card',
        stackable = true,
        handleColor = Color3.fromRGB(149, 236, 255),
        accentColor = Color3.fromRGB(235, 252, 255),
    },
}
