--!strict

return {
    field_slime_green = {
        id = 'field_slime_green',
        displayName = 'Green Slime',
        maxHealth = 44,
        experience = 18,
        bonusExperience = 12,
        damage = 8,
        moveSpeed = 11,
        aggroRange = 48,
        attackRange = 7,
        attackCooldown = 1.5,
        size = 4.5,
        color = Color3.fromRGB(88, 209, 118),
        material = Enum.Material.SmoothPlastic,
        dropTableId = 'field_slime_green',
        templateName = 'GreenSlime',
        movementProfile = {
            weaveAmplitude = 0.18,
            strafeWeight = 0.12,
            orbitWeight = 0.08,
            burstMultiplier = 1.06,
            roamRadius = 12,
        },
    },
    field_slime_blue = {
        id = 'field_slime_blue',
        displayName = 'Blue Slime',
        maxHealth = 58,
        experience = 24,
        bonusExperience = 15,
        damage = 10,
        moveSpeed = 12,
        aggroRange = 52,
        attackRange = 7,
        attackCooldown = 1.4,
        size = 4.8,
        color = Color3.fromRGB(83, 171, 255),
        material = Enum.Material.SmoothPlastic,
        dropTableId = 'field_slime_blue',
        templateName = 'BlueSlime',
        movementProfile = {
            weaveAmplitude = 0.22,
            strafeWeight = 0.18,
            orbitWeight = 0.12,
            burstMultiplier = 1.1,
            roamRadius = 14,
        },
    },
    field_slime_red = {
        id = 'field_slime_red',
        displayName = 'Red Slime',
        maxHealth = 70,
        experience = 32,
        bonusExperience = 18,
        damage = 12,
        moveSpeed = 13,
        aggroRange = 56,
        attackRange = 8,
        attackCooldown = 1.3,
        size = 5.1,
        color = Color3.fromRGB(255, 108, 122),
        material = Enum.Material.SmoothPlastic,
        dropTableId = 'field_slime_red',
        templateName = 'RedSlime',
        movementProfile = {
            weaveAmplitude = 0.26,
            strafeWeight = 0.24,
            orbitWeight = 0.16,
            burstMultiplier = 1.16,
            roamRadius = 16,
        },
    },
    icemoon_frostfang = {
        id = 'icemoon_frostfang',
        displayName = 'Frostfang Lupus',
        maxHealth = 86,
        experience = 44,
        bonusExperience = 22,
        damage = 15,
        moveSpeed = 14,
        aggroRange = 62,
        attackRange = 8,
        attackCooldown = 1.2,
        size = 5.8,
        color = Color3.fromRGB(177, 237, 255),
        material = Enum.Material.Ice,
        dropTableId = 'icemoon_frostfang',
        templateName = 'IceMoonFrostfang',
        attackStyle = 'pounce',
        specialCooldown = 4.2,
        specialRange = 26,
        specialDamage = 24,
        attackEffect = 'FrostPounce',
        attackColor = Color3.fromRGB(192, 245, 255),
        deathColor = Color3.fromRGB(192, 245, 255),
        attackSoundId = 'rbxassetid://94247729',
        attackSoundVolume = 0.58,
        attackSoundSpeed = 0.86,
        movementProfile = {
            weaveAmplitude = 0.28,
            strafeWeight = 0.26,
            orbitWeight = 0.18,
            burstMultiplier = 1.2,
            roamRadius = 18,
        },
        scaleRange = { 0.92, 1.16 },
        tintPalette = {
            Color3.fromRGB(177, 237, 255),
            Color3.fromRGB(196, 245, 255),
            Color3.fromRGB(150, 219, 255),
        },
        eyePalette = {
            Color3.fromRGB(210, 250, 255),
            Color3.fromRGB(164, 236, 255),
        },
    },
    icemoon_moonpetal = {
        id = 'icemoon_moonpetal',
        displayName = 'Moonpetal Stalker',
        maxHealth = 94,
        experience = 50,
        bonusExperience = 26,
        damage = 17,
        moveSpeed = 13,
        aggroRange = 64,
        attackRange = 8,
        attackCooldown = 1.25,
        size = 6.2,
        color = Color3.fromRGB(189, 243, 214),
        material = Enum.Material.SmoothPlastic,
        dropTableId = 'icemoon_moonpetal',
        templateName = 'IceMoonMoonpetal',
        attackStyle = 'bolt',
        specialCooldown = 3.4,
        specialRange = 34,
        specialDamage = 20,
        attackEffect = 'PetalBolt',
        attackColor = Color3.fromRGB(214, 255, 229),
        deathColor = Color3.fromRGB(214, 255, 229),
        attackSoundId = 'rbxassetid://5020159109',
        attackSoundVolume = 0.5,
        attackSoundSpeed = 1.08,
        movementProfile = {
            weaveAmplitude = 0.34,
            strafeWeight = 0.34,
            orbitWeight = 0.28,
            burstMultiplier = 1.14,
            roamRadius = 20,
        },
        scaleRange = { 0.9, 1.12 },
        tintPalette = {
            Color3.fromRGB(189, 243, 214),
            Color3.fromRGB(217, 255, 236),
            Color3.fromRGB(169, 228, 198),
        },
        eyePalette = {
            Color3.fromRGB(236, 255, 243),
            Color3.fromRGB(186, 255, 215),
        },
    },
    icemoon_shardhorn = {
        id = 'icemoon_shardhorn',
        displayName = 'Shardhorn Grazer',
        maxHealth = 118,
        experience = 58,
        bonusExperience = 30,
        damage = 20,
        moveSpeed = 12,
        aggroRange = 68,
        attackRange = 9,
        attackCooldown = 1.35,
        size = 7.6,
        color = Color3.fromRGB(149, 224, 255),
        material = Enum.Material.Glass,
        dropTableId = 'icemoon_shardhorn',
        templateName = 'IceMoonShardhorn',
        attackStyle = 'charge',
        specialCooldown = 4.8,
        specialRange = 24,
        specialDamage = 28,
        attackEffect = 'ShardCharge',
        attackColor = Color3.fromRGB(149, 224, 255),
        deathColor = Color3.fromRGB(196, 244, 255),
        attackSoundId = 'rbxassetid://5568458684',
        attackSoundVolume = 0.6,
        attackSoundSpeed = 0.74,
        movementProfile = {
            weaveAmplitude = 0.2,
            strafeWeight = 0.1,
            orbitWeight = 0.26,
            burstMultiplier = 1.24,
            roamRadius = 16,
        },
        scaleRange = { 0.94, 1.22 },
        tintPalette = {
            Color3.fromRGB(149, 224, 255),
            Color3.fromRGB(196, 244, 255),
            Color3.fromRGB(115, 196, 242),
        },
        eyePalette = {
            Color3.fromRGB(228, 249, 255),
            Color3.fromRGB(174, 234, 255),
        },
    },
}
