-- CombatConfig.lua
-- Path: ReplicatedStorage/Combat/CombatConfig
-- SOURCE: Copied from ChatGPT design session https://chatgpt.com/c/69e31ae1-fbc8-83ea-be7f-0989d3156054

local CombatConfig = {}

CombatConfig.Combo5 = {
	StartReturnTolerance = 5,

	Hit1 = {
		Name = "BlinkStrike",
		HitStop = 0.085,
		SlowMoScale = 0.62,
		SlowMoDuration = 0.08,
		ShakeCrackAmplitude = 0.16,
		ShakeCrackRotation = 0.8,
		ShakeCrackFrequency = 32,
		ShakeCrackDuration = 0.05,
		ShakeMassAmplitude = 0.38,
		ShakeMassRotation = 1.6,
		ShakeMassFrequency = 14,
		ShakeMassDuration = 0.14,
		FOVPunch = 3,
		BlurPulse = 0,
		Stun = 0.18,
		Knockback = 8,
		BlinkDuration = 0.04,
		SecondaryBurstDelay = 0.03,
		SecondaryBurstHitStop = 0.03,
	},

	Hit2Push = {
		Name = "PushbackLaunch",
		HitStop = 0.075,
		SlowMoScale = 0.70,
		SlowMoDuration = 0.06,
		ShakeCrackAmplitude = 0.14,
		ShakeCrackRotation = 0.7,
		ShakeCrackFrequency = 30,
		ShakeCrackDuration = 0.05,
		ShakeMassAmplitude = 0.32,
		ShakeMassRotation = 1.3,
		ShakeMassFrequency = 15,
		ShakeMassDuration = 0.12,
		FOVPunch = 2,
		BlurPulse = 0,
		Stun = 0.14,
		Knockback = 10,
		EnemyForwardPush = 5.5,
		PlayerBackwardLaunch = 9,
		PlayerVerticalLift = 6,
		LaunchDuration = 0.18,
	},

	Hit2Meteor = {
		Name = "MeteorOne",
		HitStop = 0.125,
		SlowMoScale = 0.42,
		SlowMoDuration = 0.13,
		ShakeCrackAmplitude = 0.22,
		ShakeCrackRotation = 1.2,
		ShakeCrackFrequency = 26,
		ShakeCrackDuration = 0.07,
		ShakeMassAmplitude = 0.85,
		ShakeMassRotation = 3.2,
		ShakeMassFrequency = 10,
		ShakeMassDuration = 0.24,
		FOVPunch = 5,
		BlurPulse = 4,
		BlurDuration = 0.06,
		Stun = 0.32,
		Knockback = 18,
		GroundCompression = 0.04,
	},

	Hit3 = {
		Name = "AirMeteorDrop",
		HitStop = 0.135,
		SlowMoScale = 0.36,
		SlowMoDuration = 0.15,
		ShakeCrackAmplitude = 0.26,
		ShakeCrackRotation = 1.4,
		ShakeCrackFrequency = 24,
		ShakeCrackDuration = 0.08,
		ShakeMassAmplitude = 1.10,
		ShakeMassRotation = 3.8,
		ShakeMassFrequency = 9,
		ShakeMassDuration = 0.28,
		FOVPunch = 6,
		BlurPulse = 5,
		BlurDuration = 0.08,
		Stun = 0.38,
		Knockback = 24,
		SelfLaunchUpward = 10,
		SelfLaunchDuration = 0.14,
	},

	Hit4 = {
		Name = "ReengageBlink",
		HitStop = 0.095,
		SlowMoScale = 0.55,
		SlowMoDuration = 0.09,
		ShakeCrackAmplitude = 0.18,
		ShakeCrackRotation = 0.9,
		ShakeCrackFrequency = 30,
		ShakeCrackDuration = 0.06,
		ShakeMassAmplitude = 0.45,
		ShakeMassRotation = 1.9,
		ShakeMassFrequency = 13,
		ShakeMassDuration = 0.16,
		FOVPunch = 4,
		BlurPulse = 0,
		Stun = 0.24,
		Knockback = 12,
		SecondaryBurstDelay = 0.04,
		SecondaryBurstHitStop = 0.04,
	},

	Hit5 = {
		Name = "FinalNukeDisengage",
		HitStop = 0.18,
		SlowMoScale = 0.28,
		SlowMoDuration = 0.18,
		ShakeCrackAmplitude = 0.32,
		ShakeCrackRotation = 1.8,
		ShakeCrackFrequency = 24,
		ShakeCrackDuration = 0.09,
		ShakeMassAmplitude = 1.4,
		ShakeMassRotation = 4.8,
		ShakeMassFrequency = 8,
		ShakeMassDuration = 0.32,
		FOVPunch = 8,
		BlurPulse = 6,
		BlurDuration = 0.08,
		Stun = 0.55,
		Knockback = 42,
		PlayerBackwardBlast = 14,
		ReturnDuration = 0.22,
		RecoveryDragSpeed = 0.7,
		RecoveryDragDuration = 0.30,
	},
}

return CombatConfig
