--!strict

local CardDefs = {
    poring_card = {
        id = 'poring_card',
        name = 'Poring Card',
        rarity = 'Legendary',
        sourceMonsterId = 'poring',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'poring_bubbles',
        specialEffectText = 'Cute pink bubble aura and a little extra lucky loot feel while equipped.',
        socketEffect = {
            statBonuses = { AGI = 1, LUK = 1 },
            secondaryStats = { itemFindBonus = 0.02, perfectDodgeChance = 0.003 },
        },
        flavor = 'The friendliest slime still knows how to make a player gasp.',
    },
    lunatic_card = {
        id = 'lunatic_card',
        name = 'Lunatic Card',
        rarity = 'Legendary',
        sourceMonsterId = 'lunatic',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'moon_hop',
        specialEffectText = 'Soft moonlit twinkles and a slipperier dodge line while equipped.',
        socketEffect = {
            statBonuses = { AGI = 1, DEX = 1 },
            secondaryStats = { flee = 4, perfectDodgeChance = 0.005 },
        },
        flavor = 'A harmless bunny still teaches patience and repetition.',
    },
    willow_card = {
        id = 'willow_card',
        name = 'Willow Card',
        rarity = 'Legendary',
        sourceMonsterId = 'willow',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'willow_spores',
        specialEffectText = 'Green spores drift around you and the card grants Fire Bolt Lv 1 while equipped.',
        socketEffect = {
            statBonuses = { INT = 2, VIT = 1 },
            secondaryStats = { magicAttack = 8, spRegenPerTick = 4 },
            grantedSkillId = 'fire_bolt',
            grantedSkillRank = 1,
        },
        flavor = 'Quiet roots, stubborn growth, and a little hidden power.',
    },
    rocker_card = {
        id = 'rocker_card',
        name = 'Rocker Card',
        rarity = 'Legendary',
        sourceMonsterId = 'rocker',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'rocker_rhythm',
        specialEffectText = 'Lime rhythm sparks dance around you and the card grants Improve Concentration Lv 1 while equipped.',
        socketEffect = {
            statBonuses = { AGI = 2 },
            secondaryStats = { hit = 6, aspd = 0.08 },
            grantedSkillId = 'improve_concentration',
            grantedSkillRank = 1,
        },
        flavor = 'A jumpy field menace that rewards commitment with tempo.',
    },
    andre_card = {
        id = 'andre_card',
        name = 'Andre Card',
        rarity = 'Legendary',
        sourceMonsterId = 'andre',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'andre_crimson',
        specialEffectText = 'A hot red ant aura and a free Provoke Lv 1 while the socketed gear is equipped.',
        socketEffect = {
            statBonuses = { STR = 2 },
            secondaryStats = { physicalAttack = 10, hit = 4 },
            grantedSkillId = 'provoke',
            grantedSkillRank = 1,
        },
        flavor = 'A classic ant cave reward for early dungeon grinders.',
    },
    deniro_card = {
        id = 'deniro_card',
        name = 'Deniro Card',
        rarity = 'Legendary',
        sourceMonsterId = 'deniro',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'amber_shell',
        specialEffectText = 'Warm amber shell motes and steadier sustain for tankier play.',
        socketEffect = {
            statBonuses = { VIT = 2 },
            secondaryStats = { physicalDefense = 10, magicalDefense = 4, hpRegenPerTick = 4 },
        },
        flavor = 'Sturdy, useful, and exactly the kind of card players remember.',
    },
    piere_card = {
        id = 'piere_card',
        name = 'Piere Card',
        rarity = 'Legendary',
        sourceMonsterId = 'piere',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'precision_gleam',
        specialEffectText = 'Sharp gold precision flashes and stronger crit payoff while equipped.',
        socketEffect = {
            statBonuses = { DEX = 2 },
            secondaryStats = { critChance = 0.015, hit = 8, critDamageMultiplier = 0.04 },
        },
        flavor = 'Precision and pressure in one tiny piece of luck.',
    },
    vitata_card = {
        id = 'vitata_card',
        name = 'Vitata Card',
        rarity = 'Legendary',
        sourceMonsterId = 'vitata',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'honey_glow',
        specialEffectText = 'Golden honey-glow motes and a noticeably healthier SP pool.',
        socketEffect = {
            statBonuses = { INT = 2, DEX = 1 },
            secondaryStats = { maxMana = 40, spRegenPerTick = 5 },
        },
        flavor = 'A sweet jackpot hidden in the deeper ant chambers.',
    },
    maya_purple_card = {
        id = 'maya_purple_card',
        name = 'Maya Purple Card',
        rarity = 'Mythic',
        sourceMonsterId = 'maya_purple_trial',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'shadow_veil',
        specialEffectText = 'A violet stealth veil and Cloaking Lv 1 while the armor is equipped.',
        supportedSlots = {
            Armor = true,
        },
        socketEffect = {
            statBonuses = { AGI = 2, LUK = 2 },
            secondaryStats = { critChance = 0.02, flee = 12, perfectDodgeChance = 0.01 },
            grantedSkillId = 'cloaking',
            grantedSkillRank = 1,
        },
        flavor = 'A forbidden Anthell prize that turns heavy armor into a shadow-veiled shell.',
    },
    sewer_lord_murmur_card = {
        id = 'sewer_lord_murmur_card',
        name = 'Sewer Lord Murmur Card',
        rarity = 'Mythic',
        sourceMonsterId = 'sewer_lord_murmur',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'murmur_shroud',
        specialEffectText = 'A dark sewer haze and Magnum Break Lv 1 for a little boss-trophy menace.',
        socketEffect = {
            statBonuses = { STR = 2, DEX = 1 },
            secondaryStats = { critDamageMultiplier = 0.12, upgradeLuckBonus = 0.015, physicalAttack = 8 },
            grantedSkillId = 'magnum_break',
            grantedSkillRank = 1,
        },
        flavor = 'A bragging-rights drop from an older prototype boss lane.',
    },
    lude_card = {
        id = 'lude_card',
        name = 'Lude Card',
        rarity = 'Legendary',
        sourceMonsterId = 'lude',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'toy_starlight',
        specialEffectText = 'Cute toy-starlight orbits and a little more lucky movement feel while equipped.',
        socketEffect = {
            statBonuses = { AGI = 2, LUK = 1 },
            secondaryStats = { flee = 6, itemFindBonus = 0.015, perfectDodgeChance = 0.004 },
        },
        flavor = 'A toy-town jackpot from the most deceptively cute monster in Niffheim.',
    },
    quve_card = {
        id = 'quve_card',
        name = 'Quve Card',
        rarity = 'Legendary',
        sourceMonsterId = 'quve',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'mourning_satin',
        specialEffectText = 'Dark satin ribbon motes and Cold Bolt Lv 1 while the socketed gear is equipped.',
        socketEffect = {
            statBonuses = { INT = 2, DEX = 1 },
            secondaryStats = { maxMana = 30, hit = 4 },
            grantedSkillId = 'cold_bolt',
            grantedSkillRank = 1,
        },
        flavor = 'Elegant, severe, and quietly dangerous in exactly the right way.',
    },
    hylozoist_card = {
        id = 'hylozoist_card',
        name = 'Hylozoist Card',
        rarity = 'Legendary',
        sourceMonsterId = 'hylozoist',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'puppet_strings',
        specialEffectText = 'Haunted thread wisps and Soul Strike Lv 1 while equipped.',
        socketEffect = {
            statBonuses = { INT = 2, VIT = 1 },
            secondaryStats = { magicAttack = 10, magicalDefense = 4 },
            grantedSkillId = 'soul_strike',
            grantedSkillRank = 1,
        },
        flavor = 'A card that makes your aura look like a puppet show gone wrong.',
    },
    gibbet_card = {
        id = 'gibbet_card',
        name = 'Gibbet Card',
        rarity = 'Legendary',
        sourceMonsterId = 'gibbet',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'gibbet_chains',
        specialEffectText = 'Chain-spark wisps with heavier frontline defense and regen.',
        socketEffect = {
            statBonuses = { STR = 1, VIT = 2 },
            secondaryStats = { physicalDefense = 12, hpRegenPerTick = 5 },
        },
        flavor = 'It carries the weight of a place where the dead were made into warnings.',
    },
    dullahan_card = {
        id = 'dullahan_card',
        name = 'Dullahan Card',
        rarity = 'Legendary',
        sourceMonsterId = 'dullahan',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'nightflame_helm',
        specialEffectText = 'Blue nightflames crown you and the card grants Bash Lv 1 while equipped.',
        socketEffect = {
            statBonuses = { STR = 2, DEX = 1 },
            secondaryStats = { hit = 8, critDamageMultiplier = 0.05 },
            grantedSkillId = 'bash',
            grantedSkillRank = 1,
        },
        flavor = 'A mounted execution aura boiled down into one hard, cold chip of power.',
    },
    disguise_card = {
        id = 'disguise_card',
        name = 'Disguise Card',
        rarity = 'Legendary',
        sourceMonsterId = 'disguise',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'phantom_shroud',
        specialEffectText = 'A pale phantom haze and stronger dodge pressure without fully turning invisible.',
        socketEffect = {
            statBonuses = { AGI = 2, LUK = 1 },
            secondaryStats = { flee = 10, perfectDodgeChance = 0.008 },
        },
        flavor = 'It does not make you vanish. It just makes people doubt what they saw.',
    },
    bloody_murderer_card = {
        id = 'bloody_murderer_card',
        name = 'Bloody Murderer Card',
        rarity = 'Legendary',
        sourceMonsterId = 'bloody_murderer',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'bloody_slash',
        specialEffectText = 'Red cut-trails orbit your gear with faster crit-heavy pressure.',
        socketEffect = {
            statBonuses = { AGI = 2, DEX = 1 },
            secondaryStats = { critChance = 0.018, critDamageMultiplier = 0.08, aspd = 0.06 },
        },
        flavor = "A brutal trophy card from one of Niffheim's most feared killers.",
    },
    loli_ruri_card = {
        id = 'loli_ruri_card',
        name = 'Loli Ruri Card',
        rarity = 'Legendary',
        sourceMonsterId = 'loli_ruri',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'ruri_petals',
        specialEffectText = 'Ghostly pink petals drift around you and the card grants Fire Bolt Lv 1 while equipped.',
        socketEffect = {
            statBonuses = { INT = 2, DEX = 1 },
            secondaryStats = { maxMana = 25, spRegenPerTick = 4 },
            grantedSkillId = 'fire_bolt',
            grantedSkillRank = 1,
        },
        flavor = 'Beautiful, tragic, and absolutely the kind of card players remember forever.',
    },
    lord_of_the_dead_card = {
        id = 'lord_of_the_dead_card',
        name = 'Lord of the Dead Card',
        rarity = 'Mythic',
        sourceMonsterId = 'lord_of_the_dead',
        lootCategory = 'Power',
        legendaryDrop = true,
        auraPreset = 'reaper_wisps',
        specialEffectText = 'A regal reaper aura, stronger mixed defenses, and Soul Strike Lv 2 while equipped.',
        socketEffect = {
            statBonuses = { STR = 2, INT = 2, VIT = 2, LUK = 1 },
            secondaryStats = { maxHealth = 80, maxMana = 40, critDamageMultiplier = 0.08, magicalDefense = 8 },
            grantedSkillId = 'soul_strike',
            grantedSkillRank = 2,
        },
        flavor = 'A true Niffheim crown-jewel card with the kind of presence that changes a whole build.',
    },
}

local cardMetadata = {
    poring_card = { description = 'A famous beginner jackpot that adds lucky evasion and a cute bubble aura to equipped gear.', sourceHint = 'Dropped by Poring', iconAssetId = '' },
    lunatic_card = { description = 'A classic low-level card that sharpens dodge flow and wraps you in soft moonlit twinkles.', sourceHint = 'Dropped by Lunatic', iconAssetId = '' },
    willow_card = { description = 'A calm magic-leaning card that adds INT, SP sustain, green spore visuals, and Fire Bolt Lv 1.', sourceHint = 'Dropped by Willow', iconAssetId = '' },
    rocker_card = { description = 'A speed-minded card with ASPD, lime rhythm sparks, and Improve Concentration Lv 1.', sourceHint = 'Dropped by Rocker', iconAssetId = '' },
    andre_card = { description = 'An early ant-dungeon dream card with stronger attack pressure and Provoke Lv 1.', sourceHint = 'Dropped by Andre', iconAssetId = '' },
    deniro_card = { description = 'A sturdy dungeon card that boosts defense, regen, and a warm shell-like aura.', sourceHint = 'Dropped by Deniro', iconAssetId = '' },
    piere_card = { description = 'A precision-focused ant card for DEX, crit payoff, and sharp gold hit flashes.', sourceHint = 'Dropped by Piere', iconAssetId = '' },
    vitata_card = { description = 'A sweeter jackpot card with extra SP sustain and a rich honey-glow aura.', sourceHint = 'Dropped by Vitata', iconAssetId = '' },
    maya_purple_card = { description = 'Slot into Armor to gain Lv 1 Cloaking. The stealth breaks if you get hit or attack.', sourceHint = 'Dropped by Maya Purple in Anthell', iconAssetId = '' },
    sewer_lord_murmur_card = { description = 'A Mythic sewer-boss trophy card with crit damage, upgrade luck, dark haze, and Magnum Break Lv 1.', sourceHint = 'Dropped by Sewer Lord Murmur', iconAssetId = '' },
    lude_card = { description = 'A toy-town jackpot with cute orbiting stars, extra agility, and more slippery movement feel.', sourceHint = 'Dropped by Lude', iconAssetId = '' },
    quve_card = { description = 'A dark ribbon card that adds caster precision and grants Cold Bolt Lv 1.', sourceHint = 'Dropped by Quve', iconAssetId = '' },
    hylozoist_card = { description = 'A haunted-puppet card with thread wisps, extra magic power, and Soul Strike Lv 1.', sourceHint = 'Dropped by Hylozoist', iconAssetId = '' },
    gibbet_card = { description = 'A graveyard bruiser card with chain sparks, better defense, and stronger regen.', sourceHint = 'Dropped by Gibbet', iconAssetId = '' },
    dullahan_card = { description = 'A nightflame knight card with melee precision and Bash Lv 1.', sourceHint = 'Dropped by Dullahan', iconAssetId = '' },
    disguise_card = { description = 'A phantom-haze dodge card for evasive builds that want to feel harder to pin down.', sourceHint = 'Dropped by Disguise', iconAssetId = '' },
    bloody_murderer_card = { description = 'A crit-heavy slasher card with red cut-trails and faster pressure.', sourceHint = 'Dropped by Bloody Murderer', iconAssetId = '' },
    loli_ruri_card = { description = 'A tragic haunted-princess card with petal aura, mana support, and Fire Bolt Lv 1.', sourceHint = 'Dropped by Loli Ruri', iconAssetId = '' },
    lord_of_the_dead_card = { description = 'A Mythic Niffheim boss card with regal reaper wisps, mixed survivability, and Soul Strike Lv 2.', sourceHint = 'Dropped by Lord of the Dead', iconAssetId = '' },
}

for cardId, metadata in pairs(cardMetadata) do
    local cardDef = CardDefs[cardId]
    if cardDef then
        for key, value in pairs(metadata) do
            cardDef[key] = value
        end
    end
end

return CardDefs
