--!strict

return {
    Version = 3,
    SaveStoreName = 'RagnarokOnline_V3_OneLevel',
    StartingClassId = 'knight',
    StartingWarpId = 'zoltraak',
    StartingMapId = 'Zoltraak',
    FieldWarpId = 'prontera_field',
    FieldMapId = 'PronteraField',
    BasicAttackCooldown = 0.28,
    BasicAttackRange = 10,
    BasicAttackDamageMin = 12,
    BasicAttackDamageMax = 18,
    BasicAttackMaxTargets = 1,
    BasicAttackConeDot = 0.4,
    DashCooldown = 0,
    DashDistance = 36,
    DashDuration = 0.14,
    DashLiftVelocity = 14,
    BaseJumpPower = 100,
    InfiniteJumpVelocity = 43,
    RandomTeleportCooldown = 0,
    RandomTeleportAttempts = 24,
    RandomTeleportSurfaceOffset = 4,
    RandomTeleportClearanceHeight = 8,
    RandomTeleportProbePadding = 6,
    RandomTeleportAnchorJitter = 16,
    SpawnYOffset = 4,
    EnemyTickRate = 0.12,
    EnemyNameplateDistance = 44,
    BossNameplateDistance = 82,
    WarpGateLabelDistance = 34,
    LootLifetime = 30,
    LootPromptDistance = 16,
    LootBillboardDistance = 42,
    LootPickupSoundId = 'rbxassetid://99298705791213',
    LootPickupSoundVolume = 0.8,
    NativeBackpackEnabled = true,
}
