--!strict

local SkillInputConfig = {
    rowSize = 9,
    maxRows = 2,
    hotbarOrder = {
        { index = 1, functionKey = Enum.KeyCode.F1, keyName = Enum.KeyCode.One.Name, displayKey = '1' },
        { index = 2, functionKey = Enum.KeyCode.F2, keyName = Enum.KeyCode.Two.Name, displayKey = '2' },
        { index = 3, functionKey = Enum.KeyCode.F3, keyName = Enum.KeyCode.Three.Name, displayKey = '3' },
        { index = 4, functionKey = Enum.KeyCode.F4, keyName = Enum.KeyCode.Four.Name, displayKey = '4' },
        { index = 5, functionKey = Enum.KeyCode.F5, keyName = Enum.KeyCode.Five.Name, displayKey = '5' },
        { index = 6, functionKey = Enum.KeyCode.F6, keyName = Enum.KeyCode.Six.Name, displayKey = '6' },
        { index = 7, functionKey = Enum.KeyCode.F7, keyName = Enum.KeyCode.Seven.Name, displayKey = '7' },
        { index = 8, functionKey = Enum.KeyCode.F8, keyName = Enum.KeyCode.Eight.Name, displayKey = '8' },
        { index = 9, functionKey = Enum.KeyCode.F9, keyName = Enum.KeyCode.Nine.Name, displayKey = '9' },
    },
    classBindings = {
        knight = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'dash_step',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'magnum_break',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'magnum_break', label = 'Magnum' },
                [3] = { skillId = 'blink_step', label = 'Blink' },
                [4] = { skillId = 'ice_shard', label = 'Ice' },
            },
        },
        high_knight = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'charge_break',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'magnum_break',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'magnum_break', label = 'Magnum' },
                [3] = { skillId = 'blink_step', label = 'Blink' },
                [4] = { skillId = 'charge_break', label = 'Charge' },
                [5] = { skillId = 'provoke', label = 'Provoke' },
                [6] = { skillId = 'ice_shard', label = 'Ice' },
            },
        },
        knight_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'charge_break',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'magnum_break',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'magnum_break', label = 'Magnum' },
                [3] = { skillId = 'blink_step', label = 'Blink' },
                [4] = { skillId = 'charge_break', label = 'Charge' },
                [5] = { skillId = 'provoke', label = 'Provoke' },
                [6] = { skillId = 'ice_shard', label = 'Ice' },
            },
        },
        lord_knight = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'blink_step',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'magnum_break',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'magnum_break', label = 'Magnum' },
                [3] = { skillId = 'blink_step', label = 'Blink' },
                [4] = { skillId = 'lord_sunder', label = 'Sunder' },
                [5] = { skillId = 'ice_shard', label = 'Ice' },
                [6] = { skillId = 'charge_break', label = 'Charge' },
            },
        },
        assassin = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sonic_blow',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'grimtooth',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'sonic_blow', label = 'Sonic' },
                [3] = { skillId = 'grimtooth', label = 'Grim' },
                [4] = { skillId = 'cloaking', label = 'Cloak' },
                [5] = { skillId = 'blink_step', label = 'Blink' },
            },
        },
        high_assassin = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sonic_blow',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'grimtooth',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'sonic_blow', label = 'Sonic' },
                [3] = { skillId = 'grimtooth', label = 'Grim' },
                [4] = { skillId = 'cloaking', label = 'Cloak' },
                [5] = { skillId = 'blink_step', label = 'Blink' },
            },
        },
        assassin_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sonic_blow',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'grimtooth',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'sonic_blow', label = 'Sonic' },
                [3] = { skillId = 'grimtooth', label = 'Grim' },
                [4] = { skillId = 'cloaking', label = 'Cloak' },
                [5] = { skillId = 'blink_step', label = 'Blink' },
            },
        },
        assassin_cross = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sonic_blow',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'grimtooth',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'sonic_blow', label = 'Sonic' },
                [3] = { skillId = 'grimtooth', label = 'Grim' },
                [4] = { skillId = 'cloaking', label = 'Cloak' },
                [5] = { skillId = 'enchant_deadly_poison', label = 'EDP' },
                [6] = { skillId = 'blink_step', label = 'Blink' },
            },
        },
        archer = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'double_strafe',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'arrow_shower',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'double_strafe', label = 'Strafe' },
                [3] = { skillId = 'arrow_shower', label = 'Shower' },
                [4] = { skillId = 'improve_concentration', label = 'Focus' },
            },
        },
        high_archer = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'double_strafe',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'arrow_shower',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'double_strafe', label = 'Strafe' },
                [3] = { skillId = 'arrow_shower', label = 'Shower' },
                [4] = { skillId = 'improve_concentration', label = 'Focus' },
            },
        },
        archer_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'double_strafe',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'arrow_shower',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'double_strafe', label = 'Strafe' },
                [3] = { skillId = 'arrow_shower', label = 'Shower' },
                [4] = { skillId = 'improve_concentration', label = 'Focus' },
            },
        },
        sniper = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'double_strafe',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'arrow_shower',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'double_strafe', label = 'Strafe' },
                [3] = { skillId = 'arrow_shower', label = 'Shower' },
                [4] = { skillId = 'improve_concentration', label = 'Focus' },
            },
        },
        mage = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'fire_bolt',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'cold_bolt',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'fire_bolt', label = 'Fire' },
                [3] = { skillId = 'cold_bolt', label = 'Cold' },
                [4] = { skillId = 'soul_strike', label = 'Soul' },
                [5] = { skillId = 'fire_wall', label = 'Wall' },
            },
        },
        high_mage = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'fire_bolt',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'cold_bolt',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'fire_bolt', label = 'Fire' },
                [3] = { skillId = 'cold_bolt', label = 'Cold' },
                [4] = { skillId = 'soul_strike', label = 'Soul' },
                [5] = { skillId = 'fire_wall', label = 'Wall' },
            },
        },
        mage_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'fire_bolt',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'cold_bolt',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'fire_bolt', label = 'Fire' },
                [3] = { skillId = 'cold_bolt', label = 'Cold' },
                [4] = { skillId = 'soul_strike', label = 'Soul' },
                [5] = { skillId = 'fire_wall', label = 'Wall' },
            },
        },
        warlock = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'fire_bolt',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'cold_bolt',
            hotbarSlots = {
                [1] = { skillId = 'dash_step', label = 'Dash' },
                [2] = { skillId = 'fire_bolt', label = 'Fire' },
                [3] = { skillId = 'cold_bolt', label = 'Cold' },
                [4] = { skillId = 'soul_strike', label = 'Soul' },
                [5] = { skillId = 'fire_wall', label = 'Wall' },
            },
        },
        zero = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'forward_slash',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'circular_slash',
            hotbarSlots = {
                [1] = { skillId = 'forward_slash', label = 'Forward' },
                [2] = { skillId = 'circular_slash', label = 'Circular' },
                [3] = { skillId = 'evasive_slash', label = 'Evasive' },
                [4] = { skillId = 'shadow_clone_slash', label = 'Clone' },
            },
        },
        high_zero = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'forward_slash',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'circular_slash',
            hotbarSlots = {
                [1] = { skillId = 'forward_slash', label = 'Forward' },
                [2] = { skillId = 'circular_slash', label = 'Circular' },
                [3] = { skillId = 'evasive_slash', label = 'Evasive' },
                [4] = { skillId = 'shadow_clone_slash', label = 'Clone' },
            },
        },
        zero_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'forward_slash',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'circular_slash',
            hotbarSlots = {
                [1] = { skillId = 'forward_slash', label = 'Forward' },
                [2] = { skillId = 'circular_slash', label = 'Circular' },
                [3] = { skillId = 'evasive_slash', label = 'Evasive' },
                [4] = { skillId = 'shadow_clone_slash', label = 'Clone' },
            },
        },
        transcendent_zero = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'forward_slash',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'circular_slash',
            hotbarSlots = {
                [1] = { skillId = 'forward_slash', label = 'Forward' },
                [2] = { skillId = 'circular_slash', label = 'Circular' },
                [3] = { skillId = 'evasive_slash', label = 'Evasive' },
                [4] = { skillId = 'shadow_clone_slash', label = 'Clone' },
            },
        },
        valkyrie = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sky_piercer',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'feather_barrage',
            hotbarSlots = {
                [1] = { skillId = 'divine_ascent', label = 'Ascend' },
                [2] = { skillId = 'sky_piercer', label = 'Pierce' },
                [3] = { skillId = 'feather_barrage', label = 'Feather' },
                [4] = { skillId = 'blink_step', label = 'Blink' },
            },
        },
        high_valkyrie = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sky_piercer',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'feather_barrage',
            hotbarSlots = {
                [1] = { skillId = 'divine_ascent', label = 'Ascend' },
                [2] = { skillId = 'sky_piercer', label = 'Pierce' },
                [3] = { skillId = 'feather_barrage', label = 'Feather' },
                [4] = { skillId = 'zephyr_veil', label = 'Veil' },
                [5] = { skillId = 'sonic_dive', label = 'Dive' },
                [6] = { skillId = 'gale_cutter', label = 'Gale' },
            },
        },
        valkyrie_rebirthed = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sky_piercer',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'feather_barrage',
            hotbarSlots = {
                [1] = { skillId = 'divine_ascent', label = 'Ascend' },
                [2] = { skillId = 'sky_piercer', label = 'Pierce' },
                [3] = { skillId = 'feather_barrage', label = 'Feather' },
                [4] = { skillId = 'zephyr_veil', label = 'Veil' },
                [5] = { skillId = 'sonic_dive', label = 'Dive' },
                [6] = { skillId = 'gale_cutter', label = 'Gale' },
                [7] = { skillId = 'storm_overdrive', label = 'Storm' },
            },
        },
        seraphim = {
            basicAttackMode = 'ClickEnemy',
            targetedSkillKey = Enum.KeyCode.One.Name,
            targetedSkillId = 'sky_piercer',
            splashSkillKey = Enum.KeyCode.Two.Name,
            splashSkillId = 'feather_barrage',
            hotbarSlots = {
                [1] = { skillId = 'divine_ascent', label = 'Ascend' },
                [2] = { skillId = 'sky_piercer', label = 'Pierce' },
                [3] = { skillId = 'feather_barrage', label = 'Feather' },
                [4] = { skillId = 'zephyr_veil', label = 'Veil' },
                [5] = { skillId = 'sonic_dive', label = 'Dive' },
                [6] = { skillId = 'gale_cutter', label = 'Gale' },
                [7] = { skillId = 'storm_overdrive', label = 'Storm' },
                [8] = { skillId = 'judgment_descent', label = 'Judgment' },
            },
        },
    },
}

return SkillInputConfig
