--!strict

local SkillRuntimeConfig = {
    basic_attack = {
        castType = 'Targeted',
        range = 12,
        damageType = 'Physical',
        damageMultiplier = 1.0,
        vfxStyle = 'slash',
        color = Color3.fromRGB(255, 240, 190),
    },
    ranged_basic_attack = {
        castType = 'Targeted',
        range = 18,
        damageType = 'Physical',
        damageMultiplier = 1.0,
        vfxStyle = 'projectile',
        color = Color3.fromRGB(190, 240, 255),
    },
    archer_basic_attack = {
        castType = 'Targeted',
        range = 1000000,
        damageType = 'Physical',
        damageMultiplier = 1.0,
        vfxStyle = 'projectile',
        color = Color3.fromRGB(248, 248, 255),
    },
    dash_step = {
        castType = 'Instant',
        range = 0,
        dashDistance = 16,
        cooldownSeconds = 0.075,
        vfxStyle = 'dash',
        color = Color3.fromRGB(255, 255, 255),
    },
    teleport = {
        castType = 'Instant',
        range = 0,
        cooldownSeconds = 0.01,
        vfxStyle = 'teleport',
        color = Color3.fromRGB(212, 236, 255),
    },
    blink_step = {
        castType = 'Targeted',
        range = 1000,
        dashDistance = 1000,
        cooldownSeconds = 6,
        damageType = 'Physical',
        damageMultiplier = 1.35,
        vfxStyle = 'blink',
        color = Color3.fromRGB(149, 213, 255),
    },

    bash = {
        castType = 'Targeted',
        range = 11,
        damageType = 'Physical',
        damageMultiplierBase = 1.0,
        damageMultiplierPerRank = 0.3,
        manaCostBase = 5,
        manaCostPerRank = 1,
        cooldownSeconds = 0.5,
        vfxStyle = 'impact',
        color = Color3.fromRGB(255, 210, 120),
    },
    magnum_break = {
        castType = 'Splash',
        radius = 14,
        damageType = 'Physical',
        damageMultiplierBase = 1.0,
        damageMultiplierPerRank = 0.2,
        manaCostBase = 20,
        manaCostPerRank = 2,
        cooldownSeconds = 2.0,
        vfxStyle = 'nova',
        color = Color3.fromRGB(255, 136, 74),
    },
    provoke = {
        castType = 'Targeted',
        range = 11,
        manaCostBase = 5,
        manaCostPerRank = 1,
        cooldownSeconds = 1.0,
        durationBase = 15,
        durationPerRank = 0,
        defenseReductionPerRank = 0.05,
        vfxStyle = 'impact',
        color = Color3.fromRGB(255, 160, 120),
    },
    ice_shard = {
        castType = 'Targeted',
        range = 120,
        damageType = 'Magic',
        hitCountBase = 5,
        hitCountPerTwoRanks = 1,
        damageMultiplierPerHitBase = 0.42,
        damageMultiplierPerHitPerRank = 0.06,
        manaCostBase = 14,
        manaCostPerRank = 1,
        cooldownSeconds = 4.5,
        castTimeBase = 0.2,
        vfxStyle = 'projectileBurst',
        color = Color3.fromRGB(162, 231, 255),
        effectProfile = 'ice_shard',
        projectileMeshAssetId = 'rbxassetid://1504522132',
        hitSoundId = 'rbxassetid://5859341051',
        explosionRadius = 5,
        shardSpread = 3.2,
    },
    charge_break = {
        castType = 'Targeted',
        range = 1000000,
        dashDistance = 1000000,
        damageType = 'Physical',
        damageMultiplierBase = 1.8,
        damageMultiplierPerRank = 0.35,
        manaCostBase = 24,
        manaCostPerRank = 2,
        cooldownSeconds = 2.5,
        vfxStyle = 'dash',
        color = Color3.fromRGB(255, 176, 110),
    },
    increase_hp_recovery = {
        castType = 'Passive',
    },
    lord_sunder = {
        castType = 'Splash',
        radius = 1000000,
        damageType = 'Physical',
        damageMultiplierBase = 2.2,
        damageMultiplierPerRank = 0.4,
        manaCostBase = 40,
        manaCostPerRank = 3,
        cooldownSeconds = 5.0,
        vfxStyle = 'nova',
        color = Color3.fromRGB(255, 118, 84),
    },
    chaos_cluster = {
        castType = 'Splash',
        radius = 18,
        damageType = 'Physical',
        damageMultiplierBase = 1.9,
        damageMultiplierPerRank = 0,
        manaCostBase = 0,
        cooldownSeconds = 0,
        vfxStyle = 'nova',
        color = Color3.fromRGB(255, 88, 72),
    },
    unwing_flyers = {
        castType = 'Targeted',
        range = 26,
        dashDistance = 8,
        damageType = 'Physical',
        damageMultiplierBase = 1.45,
        damageMultiplierPerRank = 0,
        manaCostBase = 0,
        cooldownSeconds = 0,
        vfxStyle = 'dashImpact',
        color = Color3.fromRGB(255, 116, 86),
    },

    katar_mastery = {
        castType = 'Passive',
    },
    cloaking = {
        castType = 'Instant',
        manaCostBase = 15,
        manaCostPerRank = 1,
        cooldownSeconds = 12,
        durationBase = 8,
        durationPerRank = 2,
        vfxStyle = 'dash',
        color = Color3.fromRGB(153, 153, 184),
    },
    grimtooth = {
        castType = 'Targeted',
        range = 18,
        radius = 7,
        damageType = 'Physical',
        damageMultiplierBase = 1.0,
        damageMultiplierPerRank = 0.22,
        manaCostBase = 14,
        manaCostPerRank = 1,
        cooldownSeconds = 3.5,
        vfxStyle = 'nova',
        color = Color3.fromRGB(114, 197, 161),
    },
    sonic_blow = {
        castType = 'Targeted',
        range = 12,
        dashDistance = 8,
        damageType = 'Physical',
        hitCountBase = 8,
        damageMultiplierPerHitBase = 0.35,
        damageMultiplierPerHitPerRank = 0.115,
        manaCostBase = 18,
        manaCostPerRank = 2,
        cooldownSeconds = 6.0,
        vfxStyle = 'dashImpact',
        color = Color3.fromRGB(226, 112, 168),
    },
    advanced_katar_mastery = {
        castType = 'Passive',
    },
    enchant_deadly_poison = {
        castType = 'Instant',
        manaCostBase = 30,
        manaCostPerRank = 3,
        cooldownSeconds = 30.0,
        durationBase = 18,
        durationPerRank = 4,
        vfxStyle = 'dashImpact',
        color = Color3.fromRGB(164, 255, 132),
    },

    fire_bolt = {
        castType = 'Targeted',
        range = 20,
        damageType = 'Magic',
        hitCountBase = 1,
        damageMultiplierPerHit = 1.0,
        manaCostBase = 10,
        manaCostPerRank = 2,
        cooldownSeconds = 0.5,
        castTimeBase = 0.5,
        castTimePerRank = 0.3,
        vfxStyle = 'projectile',
        color = Color3.fromRGB(255, 130, 80),
    },
    cold_bolt = {
        castType = 'Targeted',
        range = 20,
        damageType = 'Magic',
        hitCountBase = 1,
        damageMultiplierPerHit = 1.0,
        manaCostBase = 10,
        manaCostPerRank = 2,
        cooldownSeconds = 0.5,
        castTimeBase = 0.5,
        castTimePerRank = 0.3,
        vfxStyle = 'projectile',
        color = Color3.fromRGB(120, 210, 255),
    },
    soul_strike = {
        castType = 'Targeted',
        range = 20,
        damageType = 'Magic',
        hitCountFormula = 'SoulStrike',
        damageMultiplierPerHit = 0.5,
        manaCostBase = 8,
        manaCostPerRank = 2,
        cooldownSeconds = 0.6,
        castTimeBase = 0.3,
        castTimePerRank = 0.2,
        vfxStyle = 'projectileBurst',
        color = Color3.fromRGB(194, 130, 255),
    },
    fire_wall = {
        castType = 'Targeted',
        range = 15,
        radius = 6,
        damageType = 'Magic',
        hitCountBase = 3,
        damageMultiplierPerHit = 0.5,
        manaCostBase = 25,
        manaCostPerRank = 2,
        cooldownSeconds = 2.0,
        castTimeBase = 1.0,
        knockbackDistance = 6,
        vfxStyle = 'nova',
        persistSeconds = 7,
        textureAssetId = 'rbxassetid://10383034781',
        color = Color3.fromRGB(255, 110, 70),
    },
    dark_bolt = {
        castType = 'Targeted',
        range = 28,
        damageType = 'Magic',
        damageMultiplier = 0.92,
        cooldownSeconds = 3.2,
        vfxStyle = 'projectile',
        color = Color3.fromRGB(158, 118, 255),
    },
    shadow_lunge = {
        castType = 'Targeted',
        range = 22,
        dashDistance = 10,
        damageType = 'Physical',
        damageMultiplier = 1.18,
        cooldownSeconds = 4.2,
        vfxStyle = 'dashImpact',
        color = Color3.fromRGB(196, 206, 255),
    },
    cleave_arc = {
        castType = 'Targeted',
        range = 9,
        radius = 5,
        damageType = 'Physical',
        damageMultiplier = 1.08,
        cooldownSeconds = 4.6,
        vfxStyle = 'slash',
        color = Color3.fromRGB(228, 238, 255),
    },
    cursed_burst = {
        castType = 'Targeted',
        range = 18,
        radius = 8,
        damageType = 'Magic',
        damageMultiplier = 1.06,
        cooldownSeconds = 6.4,
        vfxStyle = 'nova',
        color = Color3.fromRGB(118, 88, 176),
    },

    double_strafe = {
        castType = 'Targeted',
        range = 18,
        damageType = 'Physical',
        hitCountBase = 2,
        damageMultiplierPerHitBase = 1.0,
        damageMultiplierPerHitPerRank = 0.1,
        manaCostBase = 8,
        manaCostPerRank = 1,
        cooldownSeconds = 0.3,
        vfxStyle = 'projectileBurst',
        color = Color3.fromRGB(180, 255, 200),
    },
    arrow_shower = {
        castType = 'Targeted',
        range = 18,
        radius = 6,
        damageType = 'Physical',
        damageMultiplierBase = 0.5,
        damageMultiplierPerRank = 0.1,
        manaCostBase = 12,
        manaCostPerRank = 2,
        cooldownSeconds = 1.5,
        vfxStyle = 'rain',
        color = Color3.fromRGB(160, 235, 170),
    },
    improve_concentration = {
        castType = 'Instant',
        manaCostBase = 15,
        manaCostPerRank = 2,
        cooldownSeconds = 60,
        durationBase = 30,
        durationPerRank = 10,
        vfxStyle = 'dash',
        color = Color3.fromRGB(196, 255, 196),
    },
    owls_eye = {
        castType = 'Passive',
    },
    forward_slash = {
        castType = 'Splash',
        range = 26,
        radius = 8,
        dashDistance = 22,
        damageType = 'Physical',
        damageMultiplierBase = 1.02,
        damageMultiplierPerRank = 0.14,
        manaCostBase = 6,
        manaCostPerRank = 1,
        cooldownSeconds = 0.28,
        vfxStyle = 'zeroAuthored',
        color = Color3.fromRGB(196, 244, 255),
        effectProfile = 'rift_drive',
        phaseTimings = { anticipation = 0.06, travel = 0.08, impact = 0.08, recovery = 0.16 },
        movementProfile = { mode = 'lunge', distance = 22 },
        hitboxProfile = { mode = 'rect', length = 22, width = 8 },
        comboWindowSeconds = 0.9,
    },
    circular_slash = {
        castType = 'Splash',
        radius = 14,
        dashDistance = 12,
        launchHeight = 18,
        damageType = 'Physical',
        damageMultiplierBase = 1.08,
        damageMultiplierPerRank = 0.15,
        manaCostBase = 9,
        manaCostPerRank = 1,
        cooldownSeconds = 0.28,
        vfxStyle = 'zeroAuthored',
        color = Color3.fromRGB(176, 226, 255),
        effectProfile = 'falling_halo',
        phaseTimings = { anticipation = 0.08, travel = 0.14, impact = 0.1, recovery = 0.18 },
        movementProfile = { mode = 'projected_slam', projectedDistance = 12, launchHeight = 18 },
        hitboxProfile = { mode = 'circle', radius = 14 },
        comboWindowSeconds = 0.9,
    },
    evasive_slash = {
        castType = 'Splash',
        range = 18,
        radius = 12,
        dashDistance = 16,
        damageType = 'Physical',
        damageMultiplierBase = 1.18,
        damageMultiplierPerRank = 0.16,
        manaCostBase = 10,
        manaCostPerRank = 1,
        cooldownSeconds = 0.28,
        vfxStyle = 'zeroAuthored',
        color = Color3.fromRGB(146, 200, 255),
        effectProfile = 'backstep_rend',
        phaseTimings = { anticipation = 0.04, travel = 0.07, impact = 0.07, recovery = 0.14 },
        movementProfile = { mode = 'backstep', distance = 16, evadeSeconds = 0.12 },
        hitboxProfile = { mode = 'cone', length = 13, halfAngle = 54 },
        comboWindowSeconds = 0.9,
    },
    shadow_clone_slash = {
        castType = 'Instant',
        range = 36,
        dashDistance = 24,
        damageType = 'Physical',
        hitCountBase = 3,
        damageMultiplierPerHitBase = 0.48,
        damageMultiplierPerHitPerRank = 0.07,
        finisherDamageMultiplierBase = 1.18,
        finisherDamageMultiplierPerRank = 0.12,
        manaCostBase = 20,
        manaCostPerRank = 2,
        cooldownSeconds = 1.25,
        vfxStyle = 'zeroAuthored',
        color = Color3.fromRGB(168, 182, 255),
        effectProfile = 'twin_eclipse',
        phaseTimings = { anticipation = 0.06, travel = 0.08, impact = 0.12, recovery = 0.18 },
        movementProfile = { mode = 'blink_execute', dashDistance = 24, fallbackDistance = 14 },
        hitboxProfile = { mode = 'single' },
        autoAcquireNearest = true,
        comboWindowSeconds = 0.9,
    },

    divine_ascent = {
        castType = 'Instant',
        range = 0,
        cooldownSeconds = 1.0,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(220, 240, 255),
        flightToggle = true,
    },
    sky_piercer = {
        castType = 'Splash',
        range = 30,
        radius = 8,
        dashDistance = 30,
        damageType = 'Physical',
        damageMultiplierBase = 1.4,
        damageMultiplierPerRank = 0.2,
        manaCostBase = 12,
        manaCostPerRank = 2,
        cooldownSeconds = 1.5,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(200, 230, 255),
        effectProfile = 'sky_piercer',
        requiresFlight = true,
        flightStateBonus = { Boost = 2.0, Overdrive = 3.0 },
        movementProfile = { mode = 'lunge', distance = 30 },
        hitboxProfile = { mode = 'rect', length = 30, width = 8 },
    },
    feather_barrage = {
        castType = 'Targeted',
        range = 24,
        damageType = 'Physical',
        hitCountBase = 3,
        hitCountPerTwoRanks = 1,
        damageMultiplierPerHitBase = 0.6,
        damageMultiplierPerHitPerRank = 0.08,
        manaCostBase = 15,
        manaCostPerRank = 2,
        cooldownSeconds = 2.0,
        vfxStyle = 'projectileBurst',
        color = Color3.fromRGB(230, 245, 255),
        flightDamageBonus = 1.4,
    },
    zephyr_veil = {
        castType = 'Instant',
        manaCostBase = 20,
        manaCostPerRank = 2,
        cooldownSeconds = 15.0,
        durationBase = 6,
        durationPerRank = 1,
        damageReduction = 0.30,
        reflectPercent = 0.15,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(180, 230, 200),
        effectProfile = 'zephyr_veil',
        activatesGlide = true,
    },
    sonic_dive = {
        castType = 'Targeted',
        range = 40,
        radius = 12,
        dashDistance = 40,
        damageType = 'Physical',
        damageMultiplierBase = 2.0,
        damageMultiplierPerRank = 0.35,
        manaCostBase = 28,
        manaCostPerRank = 3,
        cooldownSeconds = 4.0,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(255, 210, 140),
        effectProfile = 'sonic_dive',
        requiresFlight = true,
        altitudeDamageBonus = 0.5,
        groundDestruction = true,
        autoLand = true,
        movementProfile = { mode = 'dive', speed = 150 },
        hitboxProfile = { mode = 'circle', radius = 12 },
    },
    gale_cutter = {
        castType = 'Splash',
        radius = 14,
        damageType = 'Physical',
        hitCountBase = 4,
        hitCountPerTwoRanks = 1,
        damageMultiplierPerHitBase = 0.45,
        damageMultiplierPerHitPerRank = 0.06,
        manaCostBase = 22,
        manaCostPerRank = 2,
        cooldownSeconds = 3.0,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(170, 220, 255),
        effectProfile = 'gale_cutter',
        requiresFlight = true,
        overdriveDebuff = { speedReduction = 0.30, durationSeconds = 4 },
        hitboxProfile = { mode = 'circle', radius = 14 },
    },
    storm_overdrive = {
        castType = 'Instant',
        manaCostBase = 35,
        manaCostPerRank = 3,
        cooldownSeconds = 30.0,
        durationBase = 5,
        durationPerRank = 1,
        manaCostReduction = 0.50,
        cooldownReduction = 0.30,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(255, 80, 80),
        effectProfile = 'storm_overdrive',
        instantOverdrive = true,
    },
    celestial_sovereignty = {
        castType = 'Passive',
        flightSpeedBonus = 0.25,
        overdriveDurationBonus = 3,
        explosionRadiusBonus = 0.30,
    },
    judgment_descent = {
        castType = 'Targeted',
        range = 50,
        radius = 16,
        dashDistance = 50,
        damageType = 'Physical',
        damageMultiplierBase = 4.0,
        damageMultiplierPerRank = 0.5,
        manaCostBase = 50,
        manaCostPerRank = 5,
        cooldownSeconds = 60.0,
        vfxStyle = 'valkyrieAuthored',
        color = Color3.fromRGB(255, 225, 150),
        effectProfile = 'judgment_descent',
        requiresFlight = true,
        groundDestruction = true,
        cinematicCamera = true,
        lockOnRequired = true,
        movementProfile = { mode = 'dive', speed = 200 },
        hitboxProfile = { mode = 'circle', radius = 16 },
    },
}

return SkillRuntimeConfig
