--!strict

local EnemyDefs = {
    poring = {
        id = 'poring',
        name = 'Poring',
        level = 1,
        baseHealth = 50,
        baseAttack = 10,
        baseDefense = 2,
        baseMagicDefense = 1,
        baseHit = 15,
        baseFlee = 10,
        baseCritResist = 0.0,
        baseExperience = 15,
        jobExperience = 10,
        baseZeny = 4,
        moveSpeed = 8,
        behavior = 'Passive',
        aggroRange = 0,
        visual = {
            size = Vector3.new(3.5, 3.5, 3.5),
            color = Color3.fromRGB(255, 170, 204),
            material = Enum.Material.Neon,
        },
        dropTableId = 'poring',
        cardId = 'poring_card',
    },
    lunatic = {
        id = 'lunatic',
        name = 'Lunatic',
        level = 3,
        baseHealth = 120,
        baseAttack = 20,
        baseDefense = 5,
        baseMagicDefense = 2,
        baseHit = 25,
        baseFlee = 20,
        baseCritResist = 0.0,
        baseExperience = 30,
        jobExperience = 20,
        baseZeny = 6,
        moveSpeed = 9,
        behavior = 'Passive',
        aggroRange = 0,
        visual = {
            size = Vector3.new(3.6, 3.6, 3.6),
            color = Color3.fromRGB(255, 245, 245),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'lunatic',
        cardId = 'lunatic_card',
    },
    training_dummy = {
        id = 'training_dummy',
        name = 'Practice Dummy',
        level = 1,
        enemyType = 'Practice',
        baseHealth = 50000,
        baseAttack = 0,
        baseDefense = 0,
        baseMagicDefense = 0,
        baseHit = 0,
        baseFlee = 0,
        baseCritResist = 0.0,
        baseExperience = 0,
        jobExperience = 0,
        baseZeny = 0,
        moveSpeed = 0,
        behavior = 'Passive',
        aggroRange = 0,
        infiniteHealth = true,
        autoRefillHealth = true,
        visual = {
            size = Vector3.new(4.2, 8.5, 4.2),
            color = Color3.fromRGB(210, 178, 126),
            material = Enum.Material.WoodPlanks,
            shape = Enum.PartType.Block,
        },
    },
    willow = {
        id = 'willow',
        name = 'Willow',
        level = 5,
        baseHealth = 220,
        baseAttack = 30,
        baseDefense = 10,
        baseMagicDefense = 4,
        baseHit = 35,
        baseFlee = 15,
        baseCritResist = 0.0,
        baseExperience = 55,
        jobExperience = 35,
        baseZeny = 10,
        moveSpeed = 7,
        behavior = 'Passive',
        aggroRange = 0,
        visual = {
            size = Vector3.new(4.6, 4.6, 4.6),
            color = Color3.fromRGB(133, 196, 118),
            material = Enum.Material.WoodPlanks,
        },
        dropTableId = 'willow',
        cardId = 'willow_card',
    },
    rocker = {
        id = 'rocker',
        name = 'Rocker',
        level = 9,
        baseHealth = 450,
        baseAttack = 55,
        baseDefense = 15,
        baseMagicDefense = 6,
        baseHit = 50,
        baseFlee = 30,
        baseCritResist = 0.01,
        baseExperience = 110,
        jobExperience = 75,
        baseZeny = 18,
        moveSpeed = 11,
        behavior = 'Aggressive',
        aggroRange = 15,
        visual = {
            size = Vector3.new(4.5, 4.5, 4.5),
            color = Color3.fromRGB(114, 255, 128),
            material = Enum.Material.Neon,
        },
        dropTableId = 'rocker',
        cardId = 'rocker_card',
    },
    andre = {
        id = 'andre',
        name = 'Andre',
        level = 15,
        baseHealth = 800,
        baseAttack = 90,
        baseDefense = 25,
        baseMagicDefense = 10,
        baseHit = 70,
        baseFlee = 45,
        baseCritResist = 0.03,
        baseExperience = 250,
        jobExperience = 170,
        baseZeny = 34,
        moveSpeed = 10,
        behavior = 'Aggressive',
        aggroRange = 15,
        visual = {
            size = Vector3.new(4.8, 4.8, 4.8),
            color = Color3.fromRGB(171, 123, 78),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'andre',
        cardId = 'andre_card',
    },
    deniro = {
        id = 'deniro',
        name = 'Deniro',
        level = 17,
        baseHealth = 1000,
        baseAttack = 110,
        baseDefense = 30,
        baseMagicDefense = 12,
        baseHit = 80,
        baseFlee = 50,
        baseCritResist = 0.04,
        baseExperience = 320,
        jobExperience = 220,
        baseZeny = 40,
        moveSpeed = 10,
        behavior = 'Aggressive',
        aggroRange = 15,
        visual = {
            size = Vector3.new(5.1, 5.1, 5.1),
            color = Color3.fromRGB(196, 152, 92),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'deniro',
        cardId = 'deniro_card',
    },
    piere = {
        id = 'piere',
        name = 'Piere',
        level = 19,
        baseHealth = 1200,
        baseAttack = 130,
        baseDefense = 35,
        baseMagicDefense = 14,
        baseHit = 90,
        baseFlee = 55,
        baseCritResist = 0.05,
        baseExperience = 400,
        jobExperience = 280,
        baseZeny = 48,
        moveSpeed = 10,
        behavior = 'Aggressive',
        aggroRange = 15,
        visual = {
            size = Vector3.new(5.3, 5.3, 5.3),
            color = Color3.fromRGB(215, 182, 92),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'piere',
        cardId = 'piere_card',
    },
    vitata = {
        id = 'vitata',
        name = 'Vitata',
        level = 22,
        baseHealth = 1600,
        baseAttack = 160,
        baseDefense = 40,
        baseMagicDefense = 16,
        baseHit = 105,
        baseFlee = 65,
        baseCritResist = 0.06,
        baseExperience = 520,
        jobExperience = 360,
        baseZeny = 65,
        moveSpeed = 12,
        behavior = 'Aggressive',
        aggroRange = 18,
        visual = {
            size = Vector3.new(5.8, 5.8, 5.8),
            color = Color3.fromRGB(245, 208, 82),
            material = Enum.Material.Neon,
        },
        dropTableId = 'vitata',
        cardId = 'vitata_card',
    },
    maya_purple_trial = {
        id = 'maya_purple_trial',
        name = 'Maya Purple',
        level = 32,
        enemyType = 'Boss',
        baseHealth = 16000,
        baseAttack = 145,
        baseDefense = 52,
        baseMagicDefense = 36,
        baseHit = 240,
        baseFlee = 48,
        baseCritResist = 0.08,
        baseExperience = 1800,
        jobExperience = 1200,
        baseZeny = 220,
        moveSpeed = 10,
        behavior = 'Aggressive',
        aggroRange = 18,
        visual = {
            size = Vector3.new(8, 8, 8),
            color = Color3.fromRGB(152, 102, 255),
            material = Enum.Material.Neon,
        },
        dropTableId = 'maya_purple_trial',
        cardId = 'maya_purple_card',
        bossDropGroupId = 'maya_purple_trial',
        attackSet = {
            {
                id = 'claw_slam',
                windUpDuration = 0.7,
                isParryable = true,
                rangeStuds = 16,
            },
            {
                id = 'venom_burst',
                windUpDuration = 0.8,
                isParryable = true,
                rangeStuds = 22,
            },
            -- fire_wall is already handled via activeSkills and is NOT parryable
        },
        activeSkills = {
            {
                skillId = 'fire_wall',
                cooldownSeconds = 8.4,
                clusterCount = 3,
                randomClusterRadius = 13,
                persistSeconds = 7,
                preferredMinDistance = 5,
                range = 16,
            },
        },
    },
    sewer_lord_murmur = {
        id = 'sewer_lord_murmur',
        name = 'Sewer Lord Murmur',
        level = 6,
        enemyType = 'Boss',
        baseHealth = 420,
        baseAttack = 24,
        baseDefense = 10,
        baseMagicDefense = 8,
        baseHit = 112,
        baseFlee = 14,
        baseCritResist = 0.04,
        baseExperience = 120,
        jobExperience = 85,
        baseZeny = 24,
        moveSpeed = 9,
        behavior = 'Aggressive',
        aggroRange = 15,
        visual = {
            size = Vector3.new(7, 7, 7),
            color = Color3.fromRGB(255, 166, 92),
            material = Enum.Material.Neon,
        },
        dropTableId = 'sewer_boss_murmur',
        cardId = 'sewer_lord_murmur_card',
        bossDropGroupId = 'sewer_training_grounds',
    },
    lude = {
        id = 'lude',
        name = 'Lude',
        level = 38,
        baseHealth = 2600,
        baseAttack = 235,
        baseDefense = 42,
        baseMagicDefense = 22,
        baseHit = 155,
        baseFlee = 82,
        baseCritResist = 0.08,
        baseExperience = 1250,
        jobExperience = 880,
        baseZeny = 96,
        moveSpeed = 14,
        behavior = 'Aggressive',
        aggroRange = 22,
        visual = {
            size = Vector3.new(4.8, 4.8, 4.8),
            color = Color3.fromRGB(242, 203, 118),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'lude',
        cardId = 'lude_card',
        activeSkills = {
            {
                skillId = 'shadow_lunge',
                cooldownSeconds = 4.4,
                range = 16,
                dashDistance = 8,
            },
        },
    },
    quve = {
        id = 'quve',
        name = 'Quve',
        level = 41,
        baseHealth = 3000,
        baseAttack = 255,
        baseDefense = 46,
        baseMagicDefense = 30,
        baseHit = 170,
        baseFlee = 88,
        baseCritResist = 0.09,
        baseExperience = 1480,
        jobExperience = 1020,
        baseZeny = 108,
        moveSpeed = 12,
        behavior = 'Aggressive',
        aggroRange = 24,
        visual = {
            size = Vector3.new(5.1, 5.1, 5.1),
            color = Color3.fromRGB(208, 198, 238),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'quve',
        cardId = 'quve_card',
        activeSkills = {
            {
                skillId = 'dark_bolt',
                cooldownSeconds = 3.2,
                range = 28,
            },
        },
    },
    hylozoist = {
        id = 'hylozoist',
        name = 'Hylozoist',
        level = 44,
        baseHealth = 3600,
        baseAttack = 282,
        baseDefense = 52,
        baseMagicDefense = 34,
        baseHit = 185,
        baseFlee = 92,
        baseCritResist = 0.1,
        baseExperience = 1760,
        jobExperience = 1210,
        baseZeny = 124,
        moveSpeed = 11,
        behavior = 'Aggressive',
        aggroRange = 24,
        visual = {
            size = Vector3.new(5.3, 5.8, 5.3),
            color = Color3.fromRGB(128, 112, 168),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'hylozoist',
        cardId = 'hylozoist_card',
        activeSkills = {
            {
                skillId = 'dark_bolt',
                cooldownSeconds = 2.9,
                range = 28,
            },
            {
                skillId = 'cursed_burst',
                cooldownSeconds = 6.8,
                range = 18,
                radius = 8,
            },
        },
    },
    gibbet = {
        id = 'gibbet',
        name = 'Gibbet',
        level = 47,
        baseHealth = 4300,
        baseAttack = 315,
        baseDefense = 60,
        baseMagicDefense = 30,
        baseHit = 198,
        baseFlee = 88,
        baseCritResist = 0.11,
        baseExperience = 2090,
        jobExperience = 1420,
        baseZeny = 142,
        moveSpeed = 10,
        behavior = 'Aggressive',
        aggroRange = 26,
        visual = {
            size = Vector3.new(5.8, 7.2, 5.8),
            color = Color3.fromRGB(98, 92, 112),
            material = Enum.Material.Slate,
        },
        dropTableId = 'gibbet',
        cardId = 'gibbet_card',
        activeSkills = {
            {
                skillId = 'cleave_arc',
                cooldownSeconds = 4.8,
                range = 10,
                radius = 5,
            },
        },
    },
    dullahan = {
        id = 'dullahan',
        name = 'Dullahan',
        level = 52,
        baseHealth = 5600,
        baseAttack = 372,
        baseDefense = 66,
        baseMagicDefense = 34,
        baseHit = 218,
        baseFlee = 102,
        baseCritResist = 0.12,
        baseExperience = 2620,
        jobExperience = 1810,
        baseZeny = 178,
        moveSpeed = 13,
        behavior = 'Aggressive',
        aggroRange = 28,
        visual = {
            size = Vector3.new(6.2, 7.4, 6.2),
            color = Color3.fromRGB(76, 88, 116),
            material = Enum.Material.Metal,
        },
        dropTableId = 'dullahan',
        cardId = 'dullahan_card',
        activeSkills = {
            {
                skillId = 'shadow_lunge',
                cooldownSeconds = 4.2,
                range = 24,
                dashDistance = 11,
            },
            {
                skillId = 'cleave_arc',
                cooldownSeconds = 5.2,
                range = 10,
                radius = 6,
            },
        },
    },
    disguise = {
        id = 'disguise',
        name = 'Disguise',
        level = 49,
        baseHealth = 4100,
        baseAttack = 326,
        baseDefense = 54,
        baseMagicDefense = 32,
        baseHit = 206,
        baseFlee = 116,
        baseCritResist = 0.1,
        baseExperience = 2260,
        jobExperience = 1560,
        baseZeny = 152,
        moveSpeed = 15,
        behavior = 'Aggressive',
        aggroRange = 28,
        visual = {
            size = Vector3.new(5.4, 6.4, 5.4),
            color = Color3.fromRGB(214, 220, 238),
            material = Enum.Material.Fabric,
        },
        dropTableId = 'disguise',
        cardId = 'disguise_card',
        activeSkills = {
            {
                skillId = 'shadow_lunge',
                cooldownSeconds = 3.8,
                range = 20,
                dashDistance = 9,
            },
        },
    },
    bloody_murderer = {
        id = 'bloody_murderer',
        name = 'Bloody Murderer',
        level = 56,
        baseHealth = 6800,
        baseAttack = 418,
        baseDefense = 68,
        baseMagicDefense = 36,
        baseHit = 232,
        baseFlee = 128,
        baseCritResist = 0.14,
        baseExperience = 3140,
        jobExperience = 2140,
        baseZeny = 220,
        moveSpeed = 16,
        behavior = 'Aggressive',
        aggroRange = 30,
        visual = {
            size = Vector3.new(6.1, 7.1, 6.1),
            color = Color3.fromRGB(126, 58, 62),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'bloody_murderer',
        cardId = 'bloody_murderer_card',
        activeSkills = {
            {
                skillId = 'shadow_lunge',
                cooldownSeconds = 3.4,
                range = 22,
                dashDistance = 10,
            },
            {
                skillId = 'cleave_arc',
                cooldownSeconds = 4.2,
                range = 10,
                radius = 5,
            },
        },
    },
    loli_ruri = {
        id = 'loli_ruri',
        name = 'Loli Ruri',
        level = 54,
        baseHealth = 4700,
        baseAttack = 342,
        baseDefense = 58,
        baseMagicDefense = 46,
        baseHit = 214,
        baseFlee = 110,
        baseCritResist = 0.12,
        baseExperience = 2780,
        jobExperience = 1910,
        baseZeny = 198,
        moveSpeed = 12,
        behavior = 'Aggressive',
        aggroRange = 28,
        visual = {
            size = Vector3.new(5.6, 6.7, 5.6),
            color = Color3.fromRGB(238, 196, 216),
            material = Enum.Material.SmoothPlastic,
        },
        dropTableId = 'loli_ruri',
        cardId = 'loli_ruri_card',
        activeSkills = {
            {
                skillId = 'dark_bolt',
                cooldownSeconds = 2.7,
                range = 30,
            },
        },
    },
    lord_of_the_dead = {
        id = 'lord_of_the_dead',
        name = 'Lord of the Dead',
        level = 68,
        enemyType = 'Boss',
        baseHealth = 42000,
        baseAttack = 520,
        baseDefense = 88,
        baseMagicDefense = 62,
        baseHit = 280,
        baseFlee = 132,
        baseCritResist = 0.18,
        baseExperience = 9200,
        jobExperience = 6100,
        baseZeny = 860,
        moveSpeed = 14,
        behavior = 'Aggressive',
        aggroRange = 36,
        visual = {
            size = Vector3.new(8.4, 10.2, 8.4),
            color = Color3.fromRGB(92, 96, 122),
            material = Enum.Material.Slate,
        },
        dropTableId = 'lord_of_the_dead',
        cardId = 'lord_of_the_dead_card',
        activeSkills = {
            {
                skillId = 'dark_bolt',
                cooldownSeconds = 2.4,
                range = 34,
            },
            {
                skillId = 'cursed_burst',
                cooldownSeconds = 5.8,
                range = 22,
                radius = 9,
            },
        },
        attackSet = {
            {
                id = 'scythe_sweep',
                windUpDuration = 0.7,
                isParryable = true,
                rangeStuds = 14,
            },
            {
                id = 'death_bolt',
                windUpDuration = 0.8,
                isParryable = true,
                rangeStuds = 34,
            },
            {
                id = 'cloak_lunge',
                windUpDuration = 0.6,
                isParryable = true,
                rangeStuds = 20,
            },
            -- cursed_burst is handled via activeSkills and is NOT parryable
        },
    },
    crimson_arbiter = {
        id = 'crimson_arbiter',
        name = 'Crimson Arbiter',
        level = 82,
        enemyType = 'Boss',
        baseHealth = 78000,
        baseAttack = 680,
        baseDefense = 106,
        baseMagicDefense = 72,
        baseHit = 320,
        baseFlee = 146,
        baseCritResist = 0.22,
        baseExperience = 14000,
        jobExperience = 9200,
        baseZeny = 1200,
        moveSpeed = 16,
        behavior = 'Aggressive',
        aggroRange = 46,
        modelScale = 1.2,
        visual = {
            size = Vector3.new(20, 24, 20),
            color = Color3.fromRGB(118, 38, 46),
            material = Enum.Material.Metal,
        },
        dropTableId = 'lord_of_the_dead',
        cardId = 'lord_of_the_dead_card',
        respawnDelaySeconds = 900,
        attackSet = {
            {
                id = 'arbiter_cleave',
                windUpDuration = 0.8,
                isParryable = true,
                rangeStuds = 18,
                attackStyle = 'melee',
                damageMultiplier = 1.35,
                telegraphColor = Color3.fromRGB(255, 108, 108),
            },
            {
                id = 'arbiter_wave',
                windUpDuration = 0.9,
                isParryable = true,
                rangeStuds = 36,
                attackStyle = 'projectile',
                damageMultiplier = 1.22,
                telegraphColor = Color3.fromRGB(215, 146, 255),
            },
            {
                id = 'arbiter_crash',
                windUpDuration = 0.68,
                isParryable = true,
                rangeStuds = 26,
                attackStyle = 'lunge',
                damageMultiplier = 1.28,
                telegraphColor = Color3.fromRGB(255, 225, 155),
            },
        },
        hitboxProfile = {
            target = {
                shape = 'Box',
                size = Vector3.new(16, 22, 16),
                offset = Vector3.new(0, 2, 0),
            },
            attacks = {
                arbiter_cleave = {
                    shape = 'Box',
                    size = Vector3.new(24, 12, 26),
                    offset = Vector3.new(0, 1, -9),
                },
                arbiter_crash = {
                    shape = 'Box',
                    size = Vector3.new(18, 10, 24),
                    offset = Vector3.new(0, 1, -8),
                },
            },
        },
        activeSkills = {
            {
                skillId = 'dark_bolt',
                cooldownSeconds = 2.2,
                range = 38,
            },
            {
                skillId = 'cursed_burst',
                cooldownSeconds = 5.1,
                range = 24,
                radius = 10,
            },
            {
                skillId = 'shadow_lunge',
                cooldownSeconds = 4.0,
                range = 28,
                dashDistance = 14,
            },
            {
                skillId = 'cleave_arc',
                cooldownSeconds = 4.6,
                range = 12,
                radius = 7,
            },
        },
    },
}

return EnemyDefs
