--!strict

return {
    giant_poring = {
        id = 'giant_poring',
        displayName = 'Giant Poring',
        maxHealth = 820,
        experience = 260,
        bonusExperience = 140,
        damage = 26,
        moveSpeed = 16,
        aggroRange = 88,
        attackRange = 12,
        attackCooldown = 1.55,
        slamCooldown = 6.8,
        slamRadius = 20,
        slamDamage = 34,
        size = 12,
        color = Color3.fromRGB(255, 132, 192),
        material = Enum.Material.SmoothPlastic,
        dropTableId = 'giant_poring',
        templateName = 'GiantPoring',
        attackSoundId = 'rbxassetid://5535646989',
        attackSoundVolume = 0.72,
        attackSoundSpeed = 0.9,
        randomSpawnWithinMap = true,
        movementProfile = {
            weaveAmplitude = 0.1,
            strafeWeight = 0.08,
            orbitWeight = 0.18,
            burstMultiplier = 1.08,
            roamRadius = 24,
        },
    },
    icemoon_cryoshade = {
        id = 'icemoon_cryoshade',
        displayName = 'Cryoshade Fenrir',
        maxHealth = 980,
        experience = 340,
        bonusExperience = 180,
        damage = 32,
        moveSpeed = 15,
        aggroRange = 96,
        attackRange = 12,
        attackCooldown = 1.65,
        slamCooldown = 6.5,
        slamRadius = 22,
        slamDamage = 42,
        size = 12,
        color = Color3.fromRGB(118, 224, 255),
        material = Enum.Material.Neon,
        dropTableId = 'icemoon_cryoshade',
        templateName = 'IceMoonCryoshadeFenrir',
        deathColor = Color3.fromRGB(168, 240, 255),
        attackSoundId = 'rbxassetid://4418405082',
        attackSoundVolume = 0.78,
        attackSoundSpeed = 0.62,
        movementProfile = {
            weaveAmplitude = 0.18,
            strafeWeight = 0.22,
            orbitWeight = 0.32,
            burstMultiplier = 1.16,
            roamRadius = 26,
        },
    },
}
