--!strict

local AffixDefs = {
    prefixes = {
        fierce = {
            id = 'fierce',
            name = 'Fierce',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { STR = 2 },
            secondaryStats = { physicalAttack = 4 },
            weight = 120,
        },
        swift = {
            id = 'swift',
            name = 'Swift',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { AGI = 2, DEX = 1 },
            secondaryStats = { attackSpeedMultiplier = 0.03 },
            weight = 110,
        },
        sturdy = {
            id = 'sturdy',
            name = 'Sturdy',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { VIT = 2 },
            secondaryStats = { physicalDefense = 5 },
            weight = 115,
        },
        wise = {
            id = 'wise',
            name = 'Wise',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { INT = 2 },
            secondaryStats = { magicAttack = 4 },
            weight = 105,
        },
        precise = {
            id = 'precise',
            name = 'Precise',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { DEX = 2 },
            secondaryStats = { hit = 12 },
            weight = 100,
        },
        lucky = {
            id = 'lucky',
            name = 'Lucky',
            family = 'prefix',
            allowedItemTypes = { 'Equipment' },
            statBonuses = { LUK = 2 },
            secondaryStats = { critChance = 0.02, itemFindBonus = 0.01 },
            weight = 85,
        },
    },
    suffixes = {
        of_power = {
            id = 'of_power',
            name = 'of Power',
            family = 'suffix',
            allowedItemTypes = { 'Equipment' },
            secondaryStats = { physicalAttack = 6, critDamageMultiplier = 0.04 },
            weight = 100,
        },
        of_focus = {
            id = 'of_focus',
            name = 'of Focus',
            family = 'suffix',
            allowedItemTypes = { 'Equipment' },
            secondaryStats = { magicAttack = 6, castSpeedMultiplier = -0.03 },
            weight = 100,
        },
        of_guarding = {
            id = 'of_guarding',
            name = 'of Guarding',
            family = 'suffix',
            allowedItemTypes = { 'Equipment' },
            secondaryStats = { physicalDefense = 8, magicalDefense = 4 },
            weight = 110,
        },
        of_precision = {
            id = 'of_precision',
            name = 'of Precision',
            family = 'suffix',
            allowedItemTypes = { 'Equipment' },
            secondaryStats = { hit = 16, critChance = 0.015 },
            weight = 90,
        },
        of_fortune = {
            id = 'of_fortune',
            name = 'of Fortune',
            family = 'suffix',
            allowedItemTypes = { 'Equipment' },
            secondaryStats = { cardFindBonus = 0.012, upgradeLuckBonus = 0.01 },
            weight = 70,
        },
    },
}

return AffixDefs
