--!strict

local EquipmentDefs = {
    sword = {
        itemId = 'sword',
        attack = 25,
        weaponSpeedModifier = 1.0,
        statBonuses = { STR = 1 },
        scaling = { strength = 0.02, dexterity = 0.01 },
        secondaryStats = { hit = 4 },
        enhancementTrack = 'weapon_basic',
        cardSlots = 0,
    },
    knight_sword = {
        itemId = 'knight_sword',
        attack = 34,
        weaponSpeedModifier = 1.03,
        statBonuses = { STR = 2, DEX = 1 },
        scaling = { strength = 0.03, dexterity = 0.018 },
        secondaryStats = { hit = 8, critChance = 0.02 },
        enhancementTrack = 'weapon_basic',
        cardSlots = 0,
    },
    shadow_crescendo = {
        itemId = 'shadow_crescendo',
        attack = 28,
        weaponSpeedModifier = 1.02,
        statBonuses = { STR = 1, DEX = 1 },
        scaling = { strength = 0.025, dexterity = 0.015 },
        secondaryStats = { hit = 6 },
        enhancementTrack = 'weapon_basic',
        cardSlots = 0,
    },
    blade = {
        itemId = 'blade',
        attack = 45,
        weaponSpeedModifier = 0.96,
        statBonuses = { STR = 2, VIT = 1 },
        scaling = { strength = 0.03, dexterity = 0.01 },
        secondaryStats = { hit = 6 },
        enhancementTrack = 'weapon_basic',
        cardSlots = 1,
    },
    rod = {
        itemId = 'rod',
        attack = 10,
        weaponSpeedModifier = 1.0,
        statBonuses = { INT = 1 },
        scaling = { intelligence = 0.02, dexterity = 0.01 },
        secondaryStats = { magicAttack = 15 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 0,
    },
    wand = {
        itemId = 'wand',
        attack = 15,
        weaponSpeedModifier = 1.0,
        statBonuses = { INT = 2, DEX = 1 },
        scaling = { intelligence = 0.03, dexterity = 0.015 },
        secondaryStats = { magicAttack = 30, hit = 4 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },
    bow = {
        itemId = 'bow',
        attack = 25,
        weaponSpeedModifier = 1.02,
        statBonuses = { DEX = 1 },
        scaling = { dexterity = 0.03, agility = 0.01 },
        secondaryStats = { hit = 10 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 0,
    },
    composite_bow = {
        itemId = 'composite_bow',
        attack = 45,
        weaponSpeedModifier = 1.04,
        statBonuses = { DEX = 2, AGI = 1 },
        scaling = { dexterity = 0.035, agility = 0.012 },
        secondaryStats = { hit = 16, critChance = 0.01 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },
    katar = {
        itemId = 'katar',
        attack = 28,
        weaponSpeedModifier = 1.08,
        statBonuses = { AGI = 1, LUK = 1 },
        scaling = { agility = 0.025, dexterity = 0.015, luck = 0.01 },
        secondaryStats = { critChance = 0.03, hit = 4 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },
    cotton_shirt = {
        itemId = 'cotton_shirt',
        statBonuses = { VIT = 1 },
        secondaryStats = { physicalDefense = 5 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    padded_armor = {
        itemId = 'padded_armor',
        statBonuses = { VIT = 2 },
        secondaryStats = { physicalDefense = 15 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    leather_jacket = {
        itemId = 'leather_jacket',
        statBonuses = { VIT = 2, AGI = 1 },
        secondaryStats = { physicalDefense = 25, flee = 4 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    sandals = {
        itemId = 'sandals',
        statBonuses = { AGI = 1 },
        secondaryStats = { physicalDefense = 3 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    shoes = {
        itemId = 'shoes',
        statBonuses = { VIT = 1 },
        secondaryStats = { physicalDefense = 8 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    guard = {
        itemId = 'guard',
        statBonuses = { VIT = 1 },
        secondaryStats = { physicalDefense = 5 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    buckler = {
        itemId = 'buckler',
        statBonuses = { VIT = 1, DEX = 1 },
        secondaryStats = { physicalDefense = 10 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    mantle = {
        itemId = 'mantle',
        statBonuses = { AGI = 1, VIT = 1 },
        secondaryStats = { physicalDefense = 8, flee = 6 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    stiletto = {
        itemId = 'stiletto',
        attack = 35,
        weaponSpeedModifier = 1.06,
        statBonuses = { AGI = 1, DEX = 1 },
        scaling = { dexterity = 0.025, agility = 0.02, luck = 0.004 },
        secondaryStats = { critChance = 0.01, hit = 8 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },
    chain_mail = {
        itemId = 'chain_mail',
        statBonuses = { VIT = 3 },
        secondaryStats = { physicalDefense = 30 },
        enhancementTrack = 'armor_light',
        cardSlots = 0,
    },
    crossbow = {
        itemId = 'crossbow',
        attack = 55,
        weaponSpeedModifier = 0.98,
        statBonuses = { DEX = 2, AGI = 1 },
        scaling = { dexterity = 0.04, agility = 0.01 },
        secondaryStats = { hit = 18, critChance = 0.01 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },

    novice_sword = {
        itemId = 'novice_sword',
        attack = 8,
        weaponSpeedModifier = 1.0,
        statBonuses = { STR = 1 },
        scaling = { strength = 0.02, dexterity = 0.01, luck = 0.004 },
        secondaryStats = { critChance = 0.01 },
        enhancementTrack = 'weapon_basic',
        cardSlots = 1,
    },
    outskirts_hunter_bow = {
        itemId = 'outskirts_hunter_bow',
        attack = 16,
        weaponSpeedModifier = 1.08,
        statBonuses = { DEX = 2, AGI = 1 },
        scaling = { dexterity = 0.03, agility = 0.01, luck = 0.004 },
        secondaryStats = { hit = 18, critChance = 0.015 },
        enhancementTrack = 'weapon_precision',
        cardSlots = 1,
    },
    poring_hood = {
        itemId = 'poring_hood',
        statBonuses = { AGI = 1, LUK = 2 },
        secondaryStats = { flee = 10, critChance = 0.01, itemFindBonus = 0.01 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    murmur_blade = {
        itemId = 'murmur_blade',
        attack = 30,
        weaponSpeedModifier = 0.94,
        statBonuses = { STR = 4, DEX = 2 },
        scaling = { strength = 0.04, dexterity = 0.015, luck = 0.006 },
        secondaryStats = { critDamageMultiplier = 0.08, hit = 10 },
        enhancementTrack = 'weapon_boss',
        cardSlots = 2,
    },
    maya_purple_carapace = {
        itemId = 'maya_purple_carapace',
        statBonuses = { AGI = 2, VIT = 4, LUK = 2 },
        secondaryStats = { physicalDefense = 42, magicalDefense = 18, flee = 10, maxHealth = 120 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    murmur_mask = {
        itemId = 'murmur_mask',
        statBonuses = { VIT = 2, INT = 2, DEX = 1 },
        secondaryStats = { physicalDefense = 14, magicalDefense = 12, maxMana = 35, hit = 6 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    creepy_doll_cap = {
        itemId = 'creepy_doll_cap',
        statBonuses = { AGI = 1, LUK = 2 },
        secondaryStats = { flee = 10, itemFindBonus = 0.01, perfectDodgeChance = 0.004 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    mourning_ribbon = {
        itemId = 'mourning_ribbon',
        statBonuses = { INT = 2, DEX = 1 },
        secondaryStats = { magicalDefense = 10, maxMana = 55, spRegenPerTick = 4, hit = 6 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    puppet_coat = {
        itemId = 'puppet_coat',
        statBonuses = { INT = 2, VIT = 2 },
        secondaryStats = { physicalDefense = 22, magicalDefense = 12, magicAttack = 18 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    gibbet_armor = {
        itemId = 'gibbet_armor',
        statBonuses = { STR = 2, VIT = 3 },
        secondaryStats = { physicalDefense = 34, magicalDefense = 8, maxHealth = 75 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    dullahan_blade = {
        itemId = 'dullahan_blade',
        attack = 78,
        weaponSpeedModifier = 0.97,
        statBonuses = { STR = 3, DEX = 2 },
        scaling = { strength = 0.045, dexterity = 0.02, luck = 0.006 },
        secondaryStats = { hit = 12, critDamageMultiplier = 0.06 },
        enhancementTrack = 'weapon_boss',
        cardSlots = 1,
    },
    specter_veil = {
        itemId = 'specter_veil',
        statBonuses = { AGI = 2, LUK = 1 },
        secondaryStats = { physicalDefense = 10, flee = 14, perfectDodgeChance = 0.006 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    bloody_edge = {
        itemId = 'bloody_edge',
        attack = 84,
        weaponSpeedModifier = 1.08,
        statBonuses = { AGI = 2, DEX = 2 },
        scaling = { agility = 0.03, dexterity = 0.025, luck = 0.01 },
        secondaryStats = { hit = 10, critChance = 0.025, critDamageMultiplier = 0.08, aspd = 0.08 },
        enhancementTrack = 'weapon_boss',
        cardSlots = 2,
    },
    ruri_kimono = {
        itemId = 'ruri_kimono',
        statBonuses = { INT = 3, DEX = 2 },
        secondaryStats = { physicalDefense = 18, magicalDefense = 16, maxMana = 80, spRegenPerTick = 5 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    lord_of_dead_mantle = {
        itemId = 'lord_of_dead_mantle',
        statBonuses = { STR = 2, INT = 2, VIT = 3 },
        secondaryStats = { physicalDefense = 18, magicalDefense = 18, maxHealth = 120, maxMana = 55, critDamageMultiplier = 0.08 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
    gravebone_crown = {
        itemId = 'gravebone_crown',
        statBonuses = { VIT = 2, INT = 2, LUK = 2 },
        secondaryStats = { physicalDefense = 12, magicalDefense = 14, maxHealth = 60, maxMana = 40, hit = 8 },
        enhancementTrack = 'armor_light',
        cardSlots = 1,
    },
}

return EquipmentDefs
