--!strict

local ItemDefs = {
    sword = { id = 'sword', name = 'Sword', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 50, buyPrice = 500, sellPrice = 250, tags = { 'starter', 'weapon', 'sword', 'melee' } },
    knight_sword = { id = 'knight_sword', name = 'Knight Sword', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 50, buyPrice = 500, sellPrice = 250, tags = { 'starter', 'weapon', 'sword', 'melee', 'knight' } },
    shadow_crescendo = { id = 'shadow_crescendo', name = 'Shadow Crescendo', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Rare', weight = 52, buyPrice = 1, sellPrice = 0, tags = { 'weapon', 'sword', 'melee', 'knight', 'shadow' } },
    blade = { id = 'blade', name = 'Blade', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Uncommon', weight = 60, buyPrice = 2500, sellPrice = 1250, tags = { 'weapon', 'sword', 'melee' } },
    rod = { id = 'rod', name = 'Rod', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 40, buyPrice = 300, sellPrice = 150, tags = { 'starter', 'weapon', 'staff', 'mage' } },
    wand = { id = 'wand', name = 'Wand', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Uncommon', weight = 45, buyPrice = 1500, sellPrice = 750, tags = { 'weapon', 'staff', 'mage' } },
    bow = { id = 'bow', name = 'Bow', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 50, buyPrice = 500, sellPrice = 250, tags = { 'starter', 'weapon', 'bow', 'archer' } },
    composite_bow = { id = 'composite_bow', name = 'Composite Bow', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Uncommon', weight = 60, buyPrice = 2500, sellPrice = 1250, tags = { 'weapon', 'bow', 'archer' } },
    katar = { id = 'katar', name = 'Katar', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 45, buyPrice = 700, sellPrice = 350, tags = { 'starter', 'weapon', 'katar', 'assassin' } },
    cotton_shirt = { id = 'cotton_shirt', name = 'Cotton Shirt', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Common', weight = 10, buyPrice = 200, sellPrice = 100, tags = { 'starter', 'armor', 'light' } },
    padded_armor = { id = 'padded_armor', name = 'Padded Armor', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Uncommon', weight = 30, buyPrice = 1000, sellPrice = 500, tags = { 'armor', 'light' } },
    leather_jacket = { id = 'leather_jacket', name = 'Leather Jacket', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Rare', weight = 50, buyPrice = 3000, sellPrice = 1500, tags = { 'armor', 'light' } },
    sandals = { id = 'sandals', name = 'Sandals', itemType = 'Equipment', lootCategory = 'Power', slot = 'Shoes', rarity = 'Common', weight = 15, buyPrice = 300, sellPrice = 150, tags = { 'starter', 'shoes' } },
    shoes = { id = 'shoes', name = 'Shoes', itemType = 'Equipment', lootCategory = 'Power', slot = 'Shoes', rarity = 'Uncommon', weight = 25, buyPrice = 1000, sellPrice = 500, tags = { 'shoes' } },
    guard = { id = 'guard', name = 'Guard', itemType = 'Equipment', lootCategory = 'Power', slot = 'Shield', rarity = 'Common', weight = 30, buyPrice = 500, sellPrice = 250, tags = { 'shield' } },
    buckler = { id = 'buckler', name = 'Buckler', itemType = 'Equipment', lootCategory = 'Power', slot = 'Shield', rarity = 'Uncommon', weight = 40, buyPrice = 1500, sellPrice = 750, tags = { 'shield' } },
    mantle = { id = 'mantle', name = 'Mantle', itemType = 'Equipment', lootCategory = 'Power', slot = 'Garment', rarity = 'Rare', weight = 20, buyPrice = 0, sellPrice = 800, tags = { 'garment', 'drop_only' } },
    stiletto = { id = 'stiletto', name = 'Stiletto', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Rare', weight = 40, buyPrice = 0, sellPrice = 900, tags = { 'weapon', 'dagger', 'drop_only' } },
    chain_mail = { id = 'chain_mail', name = 'Chain Mail', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Rare', weight = 70, buyPrice = 0, sellPrice = 1400, tags = { 'armor', 'drop_only' } },
    crossbow = { id = 'crossbow', name = 'Crossbow', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Rare', weight = 55, buyPrice = 0, sellPrice = 1200, tags = { 'weapon', 'bow', 'drop_only' } },

    red_potion = { id = 'red_potion', name = 'Red Potion', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 7, buyPrice = 50, sellPrice = 25, tags = { 'healing', 'potion' } },
    orange_potion = { id = 'orange_potion', name = 'Orange Potion', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Uncommon', weight = 10, buyPrice = 200, sellPrice = 100, tags = { 'healing', 'potion' } },
    yellow_potion = { id = 'yellow_potion', name = 'Yellow Potion', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Rare', weight = 13, buyPrice = 600, sellPrice = 300, tags = { 'healing', 'potion' } },
    blue_potion = { id = 'blue_potion', name = 'Blue Potion', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 10, buyPrice = 150, sellPrice = 75, tags = { 'mana', 'potion' } },
    fly_wing = { id = 'fly_wing', name = 'Fly Wing', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 5, buyPrice = 100, sellPrice = 50, tags = { 'teleport' } },
    butterfly_wing = { id = 'butterfly_wing', name = 'Butterfly Wing', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Uncommon', weight = 5, buyPrice = 300, sellPrice = 150, tags = { 'teleport' } },
    arrow_bundle_small = { id = 'arrow_bundle_small', name = 'Arrow', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 0, buyPrice = 1, sellPrice = 0, tags = { 'ammo', 'archer' } },

    apple = { id = 'apple', name = 'Apple', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 15, tags = { 'drop', 'vendor', 'healing', 'food' } },
    jellopy = { id = 'jellopy', name = 'Jellopy', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 3, tags = { 'drop', 'vendor' } },
    empty_bottle = { id = 'empty_bottle', name = 'Empty Bottle', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 4, tags = { 'drop', 'vendor' } },
    carrot = { id = 'carrot', name = 'Carrot', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 15, tags = { 'drop', 'vendor' } },
    clover = { id = 'clover', name = 'Clover', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 10, tags = { 'drop', 'vendor' } },
    feather = { id = 'feather', name = 'Feather', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 8, tags = { 'drop', 'vendor' } },
    tree_root = { id = 'tree_root', name = 'Tree Root', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 8, tags = { 'drop', 'vendor' } },
    resin = { id = 'resin', name = 'Resin', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 20, tags = { 'drop', 'vendor' } },
    grasshopper_leg = { id = 'grasshopper_leg', name = 'Grasshopper Leg', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 12, tags = { 'drop', 'vendor' } },
    singing_flower = { id = 'singing_flower', name = 'Singing Flower', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 50, tags = { 'drop', 'vendor' } },
    shell = { id = 'shell', name = 'Shell', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 18, tags = { 'drop', 'vendor' } },
    worm_peeling = { id = 'worm_peeling', name = 'Worm Peeling', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 25, tags = { 'drop', 'vendor' } },
    chrysalis = { id = 'chrysalis', name = 'Chrysalis', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 20, tags = { 'drop', 'vendor' } },
    green_herb = { id = 'green_herb', name = 'Green Herb', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Common', weight = 3, sellPrice = 30, tags = { 'drop', 'vendor' } },
    sticky_mucus = { id = 'sticky_mucus', name = 'Sticky Mucus', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 22, tags = { 'drop', 'vendor' } },
    yellow_herb = { id = 'yellow_herb', name = 'Yellow Herb', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Uncommon', weight = 3, sellPrice = 40, tags = { 'drop', 'vendor' } },
    honey = { id = 'honey', name = 'Honey', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Uncommon', weight = 3, sellPrice = 100, tags = { 'drop', 'vendor' } },
    royal_jelly = { id = 'royal_jelly', name = 'Royal Jelly', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Rare', weight = 5, sellPrice = 500, tags = { 'drop', 'vendor', 'chase' } },

    novice_sword = { id = 'novice_sword', name = 'Novice Sword', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Common', weight = 40, sellPrice = 40, tags = { 'legacy', 'starter', 'weapon' } },
    jelly_blob = { id = 'jelly_blob', name = 'Jelly Blob', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 2, tags = { 'legacy', 'crafting', 'slime' } },
    slime_gel = { id = 'slime_gel', name = 'Slime Gel', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 4, tags = { 'legacy', 'crafting', 'vendor' } },
    green_poring_mucus = { id = 'green_poring_mucus', name = 'Green Poring Mucus', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 25, tags = { 'legacy', 'enhancement' } },
    outskirts_hunter_bow = { id = 'outskirts_hunter_bow', name = 'Outskirts Hunter Bow', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Rare', weight = 55, sellPrice = 900, tags = { 'legacy', 'bow', 'dex' } },
    poring_hood = { id = 'poring_hood', name = 'Poring Hat', itemType = 'Equipment', lootCategory = 'Power', slot = 'HeadTop', rarity = 'Rare', weight = 8, sellPrice = 700, tags = { 'poring', 'cute', 'headgear', 'agi', 'luk', 'field_chase' } },
    murmur_blade = { id = 'murmur_blade', name = 'Murmur Blade', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Epic', weight = 65, sellPrice = 1600, tags = { 'legacy', 'boss', 'str', 'dex' } },
    maya_purple_carapace = { id = 'maya_purple_carapace', name = 'Maya Purple Carapace', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Legendary', weight = 52, sellPrice = 2600, tags = { 'boss', 'anthell', 'armor', 'shadow' } },
    murmur_core = { id = 'murmur_core', name = 'Murmur Core', itemType = 'Material', lootCategory = 'Utility', rarity = 'Rare', weight = 2, sellPrice = 120, tags = { 'legacy', 'boss', 'enhancement' } },
    old_anvil_fragment = { id = 'old_anvil_fragment', name = 'Old Anvil Fragment', itemType = 'Material', lootCategory = 'Utility', rarity = 'Epic', weight = 2, sellPrice = 250, tags = { 'legacy', 'blacksmith', 'enhancement' } },
    destroyProtection = { id = 'destroyProtection', name = 'Blacksmith Ward', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Rare', weight = 1, sellPrice = 0, tags = { 'protection', 'blacksmith' } },
    downgradeProtection = { id = 'downgradeProtection', name = 'Stabilizing Flux', itemType = 'Consumable', lootCategory = 'Utility', rarity = 'Rare', weight = 1, sellPrice = 0, tags = { 'protection', 'blacksmith' } },
    premiumAnvilBlessing = { id = 'premiumAnvilBlessing', name = 'Anvil Blessing', itemType = 'Consumable', lootCategory = 'Cosmetic', rarity = 'Legendary', weight = 1, sellPrice = 0, tags = { 'protection', 'blacksmith', 'premium_optional' } },
    murmur_mask = { id = 'murmur_mask', name = 'Murmur Mask', itemType = 'Equipment', lootCategory = 'Power', slot = 'HeadMid', rarity = 'Legendary', weight = 8, sellPrice = 1800, tags = { 'boss', 'headgear', 'shadow', 'vit', 'int', 'dex' } },
    poring_balloon = { id = 'poring_balloon', name = 'Poring Balloon', itemType = 'Cosmetic', lootCategory = 'Cosmetic', rarity = 'Epic', weight = 1, sellPrice = 0, tags = { 'legacy', 'field', 'cosmetic' } },
    toy_key = { id = 'toy_key', name = 'Toy Key', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 34, tags = { 'niffheim', 'drop', 'vendor' } },
    candy_shard = { id = 'candy_shard', name = 'Candy Shard', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 36, tags = { 'niffheim', 'drop', 'vendor' } },
    creepy_doll_cap = { id = 'creepy_doll_cap', name = 'Creepy Doll Cap', itemType = 'Equipment', lootCategory = 'Power', slot = 'HeadTop', rarity = 'Rare', weight = 7, sellPrice = 980, tags = { 'niffheim', 'lude', 'headgear', 'agi', 'luk' } },
    black_ribbon = { id = 'black_ribbon', name = 'Black Ribbon', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 42, tags = { 'niffheim', 'drop', 'vendor' } },
    mourning_cloth = { id = 'mourning_cloth', name = 'Mourning Cloth', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 55, tags = { 'niffheim', 'drop', 'vendor' } },
    mourning_ribbon = { id = 'mourning_ribbon', name = 'Mourning Ribbon', itemType = 'Equipment', lootCategory = 'Power', slot = 'HeadMid', rarity = 'Rare', weight = 5, sellPrice = 1180, tags = { 'niffheim', 'quve', 'headgear', 'int', 'dex' } },
    puppet_string = { id = 'puppet_string', name = 'Puppet String', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 46, tags = { 'niffheim', 'drop', 'vendor' } },
    possessed_shard = { id = 'possessed_shard', name = 'Possessed Shard', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 66, tags = { 'niffheim', 'drop', 'vendor' } },
    puppet_coat = { id = 'puppet_coat', name = 'Puppet Coat', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Rare', weight = 36, sellPrice = 1480, tags = { 'niffheim', 'hylozoist', 'armor', 'int', 'vit' } },
    rusted_shackle = { id = 'rusted_shackle', name = 'Rusted Shackle', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 48, tags = { 'niffheim', 'drop', 'vendor' } },
    executioner_rope = { id = 'executioner_rope', name = 'Executioner Rope', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 2, sellPrice = 72, tags = { 'niffheim', 'drop', 'vendor' } },
    gibbet_armor = { id = 'gibbet_armor', name = 'Gibbet Armor', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Rare', weight = 58, sellPrice = 1720, tags = { 'niffheim', 'gibbet', 'armor', 'str', 'vit' } },
    cursed_helm_shard = { id = 'cursed_helm_shard', name = 'Cursed Helm Shard', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 2, sellPrice = 52, tags = { 'niffheim', 'drop', 'vendor' } },
    phantom_steel = { id = 'phantom_steel', name = 'Phantom Steel', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 2, sellPrice = 86, tags = { 'niffheim', 'drop', 'vendor' } },
    dullahan_blade = { id = 'dullahan_blade', name = 'Dullahan Blade', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Rare', weight = 66, sellPrice = 1880, tags = { 'niffheim', 'dullahan', 'weapon', 'str', 'dex' } },
    veil_fragment = { id = 'veil_fragment', name = 'Veil Fragment', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 44, tags = { 'niffheim', 'drop', 'vendor' } },
    phantom_cloth = { id = 'phantom_cloth', name = 'Phantom Cloth', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 70, tags = { 'niffheim', 'drop', 'vendor' } },
    specter_veil = { id = 'specter_veil', name = 'Specter Veil', itemType = 'Equipment', lootCategory = 'Power', slot = 'Garment', rarity = 'Rare', weight = 12, sellPrice = 1320, tags = { 'niffheim', 'disguise', 'garment', 'agi', 'luk' } },
    bloodied_knife_fragment = { id = 'bloodied_knife_fragment', name = 'Bloodied Knife Fragment', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 58, tags = { 'niffheim', 'drop', 'vendor' } },
    murderer_coat_scrap = { id = 'murderer_coat_scrap', name = 'Murderer Coat Scrap', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 84, tags = { 'niffheim', 'drop', 'vendor' } },
    bloody_edge = { id = 'bloody_edge', name = 'Bloody Edge', itemType = 'Equipment', lootCategory = 'Power', slot = 'Weapon', rarity = 'Epic', weight = 42, sellPrice = 2320, tags = { 'niffheim', 'bloody_murderer', 'weapon', 'agi', 'dex', 'crit' } },
    ruri_ribbon = { id = 'ruri_ribbon', name = 'Ruri Ribbon', itemType = 'Material', lootCategory = 'Utility', rarity = 'Common', weight = 1, sellPrice = 52, tags = { 'niffheim', 'drop', 'vendor' } },
    ghost_kimono_scrap = { id = 'ghost_kimono_scrap', name = 'Ghost Kimono Scrap', itemType = 'Material', lootCategory = 'Utility', rarity = 'Uncommon', weight = 1, sellPrice = 82, tags = { 'niffheim', 'drop', 'vendor' } },
    ruri_kimono = { id = 'ruri_kimono', name = 'Ruri Kimono', itemType = 'Equipment', lootCategory = 'Power', slot = 'Armor', rarity = 'Rare', weight = 28, sellPrice = 1660, tags = { 'niffheim', 'loli_ruri', 'armor', 'int', 'dex' } },
    dead_branch_relic = { id = 'dead_branch_relic', name = 'Dead Branch Relic', itemType = 'Material', lootCategory = 'Utility', rarity = 'Rare', weight = 2, sellPrice = 180, tags = { 'niffheim', 'boss', 'enhancement' } },
    reaper_lantern = { id = 'reaper_lantern', name = 'Reaper Lantern', itemType = 'Material', lootCategory = 'Utility', rarity = 'Epic', weight = 2, sellPrice = 360, tags = { 'niffheim', 'boss', 'vendor' } },
    lord_of_dead_mantle = { id = 'lord_of_dead_mantle', name = 'Lord of the Dead Mantle', itemType = 'Equipment', lootCategory = 'Power', slot = 'Garment', rarity = 'Legendary', weight = 20, sellPrice = 3200, tags = { 'niffheim', 'boss', 'garment', 'str', 'int', 'vit' } },
    gravebone_crown = { id = 'gravebone_crown', name = 'Gravebone Crown', itemType = 'Equipment', lootCategory = 'Power', slot = 'HeadTop', rarity = 'Legendary', weight = 9, sellPrice = 2800, tags = { 'niffheim', 'boss', 'headgear', 'luk', 'vit', 'int' } },
}

local itemMetadata = {
    sword = { description = 'A dependable starter sword for early melee builds.', flavor = 'Plain steel and honest reach.', sourceHint = 'Starter Knight gear', iconAssetId = '' },
    knight_sword = { description = 'A knight-only starter blade built for the front line.', flavor = 'Heavy steel, clean edge, and a proper hero silhouette.', sourceHint = 'Starter Knight gear', iconAssetId = 'rbxassetid://10288498712' },
    shadow_crescendo = { description = 'A darker twin blade that still fits a front-line knight style.', flavor = 'Cold steel wrapped in a shadowy sheen.', sourceHint = 'Roman test gear', iconAssetId = 'rbxassetid://10288446354' },
    rod = { description = 'A basic catalyst for early spellcasting.', flavor = 'Light, plain, and steady.', sourceHint = 'Starter Mage gear', iconAssetId = '' },
    bow = { description = 'A simple training bow for early ranged pressure.', flavor = 'Flexible wood and clean string tension.', sourceHint = 'Starter Archer gear', iconAssetId = '' },
    katar = { description = 'A paired claw weapon that rewards speed and crits.', flavor = 'Light in the hand and eager to carve.', sourceHint = 'Starter Assassin gear', iconAssetId = '' },
    cotton_shirt = { description = 'A simple cloth top worn by fresh adventurers.', flavor = 'Not glamorous, but dependable.', sourceHint = 'Starter path armor', iconAssetId = '' },
    sandals = { description = 'Light footwear that keeps beginners mobile.', flavor = 'Cheap soles still matter.', sourceHint = 'Starter path gear', iconAssetId = '' },
    arrow_bundle_small = { description = 'Standard bow ammunition that must be equipped in the ammo slot before archers can fire.', flavor = 'Simple shafts, steady flights, and the quiet comfort of never hearing the string snap on an empty quiver.', sourceHint = 'Starter Archer supplies', iconAssetId = '' },
    apple = { description = 'A simple field snack that can be eaten straight from the bag for a small HP restore.', flavor = 'Bruised, ordinary, and still surprisingly welcome when your health bar gets chipped down.', sourceHint = 'Often dropped by Poring', iconAssetId = '' },
    jellopy = { description = 'Sticky poring residue used as a classic vendor drop.', flavor = 'Every novice learns this blob on sight.', sourceHint = 'Often dropped by Poring', iconAssetId = '' },
    empty_bottle = { description = 'A reusable bottle shell with future utility.', flavor = 'Cheap glass, still satisfying to find.', sourceHint = 'Sometimes dropped by Poring', iconAssetId = '' },
    carrot = { description = 'A practical food drop tied to Lunatic hunting.', flavor = 'Fresh enough to sell.', sourceHint = 'Often dropped by Lunatic', iconAssetId = '' },
    clover = { description = 'A low-tier field material with a lucky feel.', flavor = 'Soft leaves and beginner charm.', sourceHint = 'Often dropped by Lunatic', iconAssetId = '' },
    feather = { description = 'A light utility material useful for selling.', flavor = 'Nearly weightless, still worth the pickup.', sourceHint = 'Sometimes dropped by Lunatic', iconAssetId = '' },
    tree_root = { description = 'A woody crafting scrap from living field trees.', flavor = 'Rough fibers and stubborn bark.', sourceHint = 'Often dropped by Willow', iconAssetId = '' },
    resin = { description = 'Sticky tree sap valued as a better Willow vendor drop.', flavor = 'Amber sap with a nice little jackpot feel.', sourceHint = 'Often dropped by Willow', iconAssetId = '' },
    grasshopper_leg = { description = 'A common insect trophy from fast field pests.', flavor = 'Proof that the hunt happened.', sourceHint = 'Often dropped by Rocker', iconAssetId = '' },
    singing_flower = { description = 'A prettier uncommon field drop with stronger vendor feel.', flavor = 'Bright petals and a little sparkle.', sourceHint = 'Sometimes dropped by Rocker', iconAssetId = '' },
    shell = { description = 'A rugged carapace fragment from the ant tunnels.', flavor = 'Chipped dungeon junk that still sells.', sourceHint = 'Often dropped by Andre', iconAssetId = '' },
    worm_peeling = { description = 'A brittle early ant-dungeon material drop.', flavor = 'Gross enough to matter, valuable enough to pocket.', sourceHint = 'Often dropped by Andre', iconAssetId = '' },
    stiletto = { description = 'A rare dagger drop with real early spike potential.', flavor = 'Slim steel and real luck.', sourceHint = 'Rarely dropped by Andre', iconAssetId = '' },
    chrysalis = { description = 'A lightweight insect shell good for crafting and selling.', flavor = 'Dry and unmistakably dungeon-born.', sourceHint = 'Often dropped by Deniro', iconAssetId = '' },
    green_herb = { description = 'A common herb with basic recovery and vendor utility.', flavor = 'A familiar drop every grind piles up.', sourceHint = 'Often dropped by Deniro', iconAssetId = '' },
    chain_mail = { description = 'A rare armor drop that feels like a real upgrade.', flavor = 'Heavy rings and honest defense.', sourceHint = 'Rarely dropped by Deniro', iconAssetId = '' },
    sticky_mucus = { description = 'A damp insect secretion with classic vendor value.', flavor = 'Slimy and weirdly satisfying when it stacks up.', sourceHint = 'Often dropped by Piere', iconAssetId = '' },
    yellow_herb = { description = 'A better herb drop that feels immediately more valuable.', flavor = 'Bright and medicinal.', sourceHint = 'Sometimes dropped by Piere', iconAssetId = '' },
    crossbow = { description = 'A rare ranged weapon drop with stronger payoff.', flavor = 'Heavier limbs and cleaner force.', sourceHint = 'Rarely dropped by Piere', iconAssetId = '' },
    honey = { description = 'A sweet uncommon loot drop from deeper ant monsters.', flavor = 'Golden, sticky, and nicer than cave grime.', sourceHint = 'Sometimes dropped by Vitata', iconAssetId = '' },
    royal_jelly = { description = 'A rarer Vitata-side prize with jackpot feel.', flavor = 'Rich, glossy, and memorable.', sourceHint = 'Rarely dropped by Vitata', iconAssetId = '' },
    mantle = { description = 'A rare garment drop with real evasive value.', flavor = 'Light cloth with drop-only prestige.', sourceHint = 'Rarely dropped by Vitata', iconAssetId = '' },
    green_poring_mucus = { description = 'A special enhancement material from tougher encounters.', flavor = 'Clearly not beginner trash anymore.', sourceHint = 'Dropped in boss or trial encounters', iconAssetId = '' },
    murmur_core = { description = 'A dense boss material with crafting and upgrade value.', flavor = 'Old, foul, and powerful.', sourceHint = 'Dropped by Sewer Lord Murmur or Maya Purple Trial', iconAssetId = '' },
    old_anvil_fragment = { description = 'A premium enhancement fragment tied to harder bosses.', flavor = 'A broken piece of forging history.', sourceHint = 'Rarely dropped in boss or trial encounters', iconAssetId = '' },
    murmur_blade = { description = 'An Epic boss weapon with real chase value.', flavor = 'A vicious relic from the sewer.', sourceHint = 'Dropped by Sewer Lord Murmur or Maya Purple Trial', iconAssetId = '' },
    maya_purple_carapace = { description = 'A shadow-soaked boss armor with one card slot and real endgame swagger.', flavor = 'Its shell seems to drink in torchlight instead of reflecting it.', sourceHint = 'Dropped by Maya Purple in Anthell', iconAssetId = '' },
    murmur_mask = { description = 'A sinister boss facepiece that now grants real combat stats as wearable headgear.', flavor = 'A sewer-born mask that hums with stale power and bad intent.', sourceHint = 'Rarely dropped by Sewer Lord Murmur', iconAssetId = '' },
    poring_hood = { description = 'A super cute pink poring hat for adventurers who want their grind to show.', flavor = 'Soft, squishy-looking, and just rare enough that wearing it feels like a small beginner-era triumph.', sourceHint = 'Mid-tier drop from Poring', iconAssetId = '' },
    toy_key = { description = 'A small toy key dropped by eerie doll-like monsters in Niffheim.', flavor = 'It feels like it should open something abandoned long ago.', sourceHint = 'Dropped by Lude', iconAssetId = '' },
    candy_shard = { description = 'A brittle haunted sweet with solid vendor value.', flavor = 'Still colorful and definitely wrong somehow.', sourceHint = 'Dropped by Lude', iconAssetId = '' },
    creepy_doll_cap = { description = 'A cute-creepy doll cap for AGI and LUK builds.', flavor = 'Adorable and cursed in the exact right ratio.', sourceHint = 'Rarely dropped by Lude', iconAssetId = '' },
    black_ribbon = { description = 'A funeral ribbon scrap from the haunted town.', flavor = 'Soft cloth with a grief-soaked elegance to it.', sourceHint = 'Dropped by Quve', iconAssetId = '' },
    mourning_cloth = { description = 'A dark cloth strip with stronger vendor value.', flavor = 'It still smells like cold nights and old perfume.', sourceHint = 'Dropped by Quve', iconAssetId = '' },
    mourning_ribbon = { description = 'A stylish ribbon for caster-leaning builds.', flavor = 'Neat, severe, and just expensive-looking enough.', sourceHint = 'Rarely dropped by Quve', iconAssetId = '' },
    puppet_string = { description = 'Taut string from a possessed puppet body.', flavor = 'It still feels like it is trying to pull something.', sourceHint = 'Dropped by Hylozoist', iconAssetId = '' },
    possessed_shard = { description = 'A jagged haunted splinter from a doll shell.', flavor = 'Cold in the hand and too heavy for its size.', sourceHint = 'Dropped by Hylozoist', iconAssetId = '' },
    puppet_coat = { description = 'A puppet-stitched coat with real caster-defense value.', flavor = 'Every seam looks hand-finished by something that never slept.', sourceHint = 'Rarely dropped by Hylozoist', iconAssetId = '' },
    rusted_shackle = { description = 'A prison scrap from the graveyard gallows line.', flavor = 'Weighty, ugly, and still stained with history.', sourceHint = 'Dropped by Gibbet', iconAssetId = '' },
    executioner_rope = { description = 'A thick rope drop from Niffheim execution monsters.', flavor = 'Frayed, stained, and impossible to mistake.', sourceHint = 'Dropped by Gibbet', iconAssetId = '' },
    gibbet_armor = { description = 'Heavy haunted armor for strength and grit.', flavor = 'Built like a prison gate and almost as subtle.', sourceHint = 'Rarely dropped by Gibbet', iconAssetId = '' },
    cursed_helm_shard = { description = 'A broken piece of ancient helm plate.', flavor = 'The metal stays cold even in torchlight.', sourceHint = 'Dropped by Dullahan', iconAssetId = '' },
    phantom_steel = { description = 'A rarer haunted alloy used by stronger drops.', flavor = 'It flashes blue at the edge like moonlight.', sourceHint = 'Dropped by Dullahan', iconAssetId = '' },
    dullahan_blade = { description = 'A rare heavy blade with real STR and DEX payoff.', flavor = "A knightly weapon still carrying its rider's rage.", sourceHint = 'Rarely dropped by Dullahan', iconAssetId = '' },
    veil_fragment = { description = 'A pale cloth fragment from a monster built on false identity.', flavor = 'Thin enough to float if you breathe on it.', sourceHint = 'Dropped by Disguise', iconAssetId = '' },
    phantom_cloth = { description = 'A ghostly fabric scrap with surprising value.', flavor = 'It catches light like it wants to disappear from it.', sourceHint = 'Dropped by Disguise', iconAssetId = '' },
    specter_veil = { description = 'A stealth-flavored garment with evade-heavy stats.', flavor = 'When it hangs still, it almost looks unworn.', sourceHint = 'Rarely dropped by Disguise', iconAssetId = '' },
    bloodied_knife_fragment = { description = 'A chipped assassin-style blade scrap from a street phantom.', flavor = 'The metal is nicked, but the intent is still sharp.', sourceHint = 'Dropped by Bloody Murderer', iconAssetId = '' },
    murderer_coat_scrap = { description = 'A strip of dark coat cloth from a murderous phantom.', flavor = 'It feels expensive in the worst possible way.', sourceHint = 'Dropped by Bloody Murderer', iconAssetId = '' },
    bloody_edge = { description = "A fast crit-oriented chase weapon from one of Niffheim's deadliest elites.", flavor = 'Too light, too eager, and built to make crits feel unfair.', sourceHint = 'Rarely dropped by Bloody Murderer', iconAssetId = '' },
    ruri_ribbon = { description = 'A pretty haunted ribbon tied to a tragic spirit.', flavor = 'Delicate and sweet-looking until you remember where it came from.', sourceHint = 'Dropped by Loli Ruri', iconAssetId = '' },
    ghost_kimono_scrap = { description = 'A kimono fragment carrying a softer haunted-town identity.', flavor = 'Thin silk with a warmth that fades the longer you hold it.', sourceHint = 'Dropped by Loli Ruri', iconAssetId = '' },
    ruri_kimono = { description = 'A rare caster robe with mana-focused stats and strong style.', flavor = 'Elegant enough to wear proudly and eerie enough to unsettle a room.', sourceHint = 'Rarely dropped by Loli Ruri', iconAssetId = '' },
    dead_branch_relic = { description = 'A boss-grade haunted relic tied to deep death magic.', flavor = 'It looks like dead wood but hums like it remembers life.', sourceHint = 'Dropped by Lord of the Dead', iconAssetId = '' },
    reaper_lantern = { description = "A rare soul lantern from Niffheim's marquee boss lane.", flavor = 'The flame inside burns without warmth and without mercy.', sourceHint = 'Dropped by Lord of the Dead', iconAssetId = '' },
    lord_of_dead_mantle = { description = 'A legendary mantle that mixes durability, intellect, and dark prestige.', flavor = 'It drapes like smoke and still somehow feels heavy.', sourceHint = 'Dropped by Lord of the Dead', iconAssetId = '' },
    gravebone_crown = { description = 'A regal death-crowned headpiece for haunted swagger.', flavor = 'Ceremonial, ancient, and a little blasphemous.', sourceHint = 'Dropped by Lord of the Dead', iconAssetId = '' },
}

for itemId, metadata in pairs(itemMetadata) do
    local itemDef = ItemDefs[itemId]
    if itemDef then
        for key, value in pairs(metadata) do
            itemDef[key] = value
        end
    end
end

return ItemDefs
