--!strict

local GameplayNetDefs = {
    RemoteEvents = {
        RequestAction = 'RequestAction',
        StateUpdated = 'StateUpdated',
        UiMessage = 'UiMessage',
        OpenWarpMenu = 'OpenWarpMenu',
        OpenRebirthMenu = 'OpenRebirthMenu',
        OpenJobChangeMenu = 'OpenJobChangeMenu',
        OpenBlacksmithMenu = 'OpenBlacksmithMenu',
        OpenShopMenu = 'OpenShopMenu',
        OpenStorePlaceholder = 'OpenStorePlaceholder',
        PlaySkillEffect = 'PlaySkillEffect',
        FlightStateChanged = 'FlightStateChanged',
        FlightEffectsReplicate = 'FlightEffectsReplicate',
        ChatMessageReceived = 'ChatMessageReceived',
        BossWindUp   = 'BossWindUp',
        ParryResult  = 'ParryResult',
    },
    RemoteFunctions = {
        GetGameState = 'GetGameState',
    },
    Actions = {
        AllocateStat = 'AllocateStat',
        BasicAttackNearest = 'BasicAttackNearest',
        BasicAttackTarget = 'BasicAttackTarget',
        EquipItemInstance = 'EquipItemInstance',
        UnequipItemInstance = 'UnequipItemInstance',
        EquipAmmoItem = 'EquipAmmoItem',
        WarpToTown = 'WarpToTown',
        WarpToField = 'WarpToField',
        WarpToDungeon = 'WarpToDungeon',
        UseTargetedSkill = 'UseTargetedSkill',
        UseSplashSkill = 'UseSplashSkill',
        UseInstantSkill = 'UseInstantSkill',
        SetHotbarSkill = 'SetHotbarSkill',
        SetHotbarItem = 'SetHotbarItem',
        UseInventoryItem = 'UseInventoryItem',
        SocketCardIntoEquipment = 'SocketCardIntoEquipment',
        InvestSkillPoint = 'InvestSkillPoint',
        HealPlayer = 'HealPlayer',
        BuyShopItem = 'BuyShopItem',
        SellInventoryItem = 'SellInventoryItem',
        PreviewEnhancement = 'PreviewEnhancement',
        RequestEnhancement = 'RequestEnhancement',
        AttemptAdvanceClass = 'AttemptAdvanceClass',
        AttemptRebirth = 'AttemptRebirth',
        ChangeArchetype = 'ChangeArchetype',
        InviteNearestPlayerToParty = 'InviteNearestPlayerToParty',
        LeaveParty = 'LeaveParty',
        SendChatMessage = 'SendChatMessage',
        OpenStorePlaceholder = 'OpenStorePlaceholder',
        CommitStatDraft = 'CommitStatDraft',
        SetCustomSkillHotkey = 'SetCustomSkillHotkey',
        AdminSetBaseStatValue = 'AdminSetBaseStatValue',
        AdminMaxAllBaseStats = 'AdminMaxAllBaseStats',
        AdminResetBaseStats = 'AdminResetBaseStats',
        AdminGrantBaseLevels = 'AdminGrantBaseLevels',
        AdminGrantJobLevels = 'AdminGrantJobLevels',
        AdminSetSkillRank = 'AdminSetSkillRank',
        AdminMaxAllSkills = 'AdminMaxAllSkills',
        AdminResetSkillOverrides = 'AdminResetSkillOverrides',
        AdminSetNoCooldowns = 'AdminSetNoCooldowns',
        ParryAction = 'ParryAction',
        ToggleFlight = 'ToggleFlight',
    },
}

return GameplayNetDefs
