--!strict

local SkillDefs = {
    dash_step = {
        id = 'dash_step',
        archetypeId = 'shared',
        classId = 'shared',
        stage = 'Shared',
        name = 'Dash Step',
        category = 'Utility',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 0.075,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'mobility', 'shared', 'dash' },
        vfx = { effectKey = 'vfx_shared_dash_step', flashinessTier = 1, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_SHARED_DASH' },
        animation = { animationKey = 'anim_shared_dash_step', futureAssetHook = 'rbxassetid://TODO_ANIM_SHARED_DASH' },
    },
    teleport = {
        id = 'teleport',
        archetypeId = 'shared',
        classId = 'shared',
        stage = 'Shared',
        name = 'Teleport',
        category = 'Utility',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 0.01,
        statScaling = { primary = 'AGI', secondary = 'INT' },
        tags = { 'mobility', 'shared', 'teleport', 'fly_wing', 'map_random' },
        vfx = { effectKey = 'vfx_shared_teleport', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_SHARED_TELEPORT' },
        animation = { animationKey = 'anim_shared_teleport', futureAssetHook = 'rbxassetid://TODO_ANIM_SHARED_TELEPORT' },
    },
    blink_step = {
        id = 'blink_step',
        archetypeId = 'shared',
        classId = 'shared',
        stage = 'Shared',
        name = 'Blink',
        category = 'Utility',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 6,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'mobility', 'shared', 'blink', 'teleport', 'targeted' },
        vfx = { effectKey = 'vfx_shared_blink_step', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_SHARED_BLINK' },
        animation = { animationKey = 'anim_shared_blink_step', futureAssetHook = 'rbxassetid://TODO_ANIM_SHARED_BLINK' },
    },

    bash = {
        id = 'bash',
        archetypeId = 'knight_path',
        classId = 'knight',
        stage = 'Base',
        name = 'Bash',
        category = 'Active',
        maxLevel = 10,
        manaCost = 5,
        cooldownSeconds = 0.5,
        statScaling = { primary = 'STR', secondary = 'DEX' },
        tags = { 'melee', 'single_target', 'physical' },
        vfx = { effectKey = 'vfx_knight_bash', flashinessTier = 1, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_KNIGHT_BASH' },
        animation = { animationKey = 'anim_knight_bash', futureAssetHook = 'rbxassetid://TODO_ANIM_KNIGHT_BASH' },
    },
    magnum_break = {
        id = 'magnum_break',
        archetypeId = 'knight_path',
        classId = 'knight',
        stage = 'Base',
        name = 'Magnum Break',
        category = 'Active',
        maxLevel = 10,
        manaCost = 20,
        cooldownSeconds = 2.0,
        statScaling = { primary = 'STR', secondary = 'VIT' },
        prerequisites = {
            { skillId = 'bash', rank = 3 },
        },
        tags = { 'melee', 'aoe', 'physical', 'fire' },
        vfx = { effectKey = 'vfx_knight_magnum_break', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_KNIGHT_MAGNUM_BREAK' },
        animation = { animationKey = 'anim_knight_magnum_break', futureAssetHook = 'rbxassetid://TODO_ANIM_KNIGHT_MAGNUM_BREAK' },
    },
    provoke = {
        id = 'provoke',
        archetypeId = 'knight_path',
        classId = 'knight',
        stage = 'Base',
        name = 'Provoke',
        category = 'Active',
        maxLevel = 10,
        manaCost = 5,
        cooldownSeconds = 1.0,
        statScaling = { primary = 'VIT', secondary = 'STR' },
        tags = { 'melee', 'debuff', 'targeted' },
        vfx = { effectKey = 'vfx_knight_provoke', flashinessTier = 1, socket = 'TargetHead', futureAssetHook = 'rbxassetid://TODO_KNIGHT_PROVOKE' },
        animation = { animationKey = 'anim_knight_provoke', futureAssetHook = 'rbxassetid://TODO_ANIM_KNIGHT_PROVOKE' },
    },
    ice_shard = {
        id = 'ice_shard',
        archetypeId = 'knight_path',
        classId = 'knight',
        stage = 'Base',
        name = 'Ice Shard',
        category = 'Active',
        maxLevel = 10,
        manaCost = 14,
        cooldownSeconds = 4.5,
        castSeconds = 0.2,
        statScaling = { primary = 'STR', secondary = 'INT' },
        tags = { 'ranged', 'magic', 'ice', 'multi_hit', 'targeted' },
        vfx = { effectKey = 'vfx_knight_ice_shard', flashinessTier = 2, socket = 'Hand', futureAssetHook = 'rbxassetid://1504522132' },
        animation = { animationKey = 'anim_knight_ice_shard', futureAssetHook = 'rbxassetid://TODO_ANIM_KNIGHT_ICE_SHARD' },
    },
    charge_break = {
        id = 'charge_break',
        archetypeId = 'knight_path',
        classId = 'high_knight',
        stage = 'High',
        name = 'Charge Break',
        category = 'Active',
        maxLevel = 10,
        manaCost = 24,
        cooldownSeconds = 2.5,
        statScaling = { primary = 'STR', secondary = 'AGI' },
        prerequisites = {
            { skillId = 'bash', rank = 5 },
        },
        tags = { 'melee', 'single_target', 'physical', 'dash', 'gap_closer' },
        vfx = { effectKey = 'vfx_knight_charge_break', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_KNIGHT_CHARGE_BREAK' },
        animation = { animationKey = 'anim_knight_charge_break', futureAssetHook = 'rbxassetid://TODO_ANIM_KNIGHT_CHARGE_BREAK' },
    },
    increase_hp_recovery = {
        id = 'increase_hp_recovery',
        archetypeId = 'knight_path',
        classId = 'knight',
        stage = 'Base',
        name = 'Increase HP Recovery',
        category = 'Passive',
        maxLevel = 10,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'VIT', secondary = 'STR' },
        tags = { 'passive', 'regen' },
        vfx = { effectKey = 'vfx_passive_hp_recovery', flashinessTier = 0, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_PASSIVE_RECOVERY' },
        animation = { animationKey = 'anim_passive', futureAssetHook = 'rbxassetid://TODO_ANIM_PASSIVE' },
    },
    lord_sunder = {
        id = 'lord_sunder',
        archetypeId = 'knight_path',
        classId = 'lord_knight',
        stage = 'Advanced',
        name = 'Lord Sunder',
        category = 'Active',
        maxLevel = 10,
        manaCost = 40,
        cooldownSeconds = 5.0,
        statScaling = { primary = 'STR', secondary = 'VIT' },
        prerequisites = {
            { skillId = 'magnum_break', rank = 5 },
            { skillId = 'charge_break', rank = 3 },
        },
        tags = { 'melee', 'aoe', 'physical', 'shockwave', 'lord_knight' },
        vfx = { effectKey = 'vfx_lord_knight_lord_sunder', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_LORD_KNIGHT_LORD_SUNDER' },
        animation = { animationKey = 'anim_lord_knight_lord_sunder', futureAssetHook = 'rbxassetid://TODO_ANIM_LORD_KNIGHT_LORD_SUNDER' },
    },
    chaos_cluster = {
        id = 'chaos_cluster',
        archetypeId = 'equipment',
        classId = 'knight_sword',
        stage = 'Equipment',
        name = 'Chaos Cluster',
        category = 'Active',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'STR', secondary = 'DEX' },
        tags = { 'equipment', 'weapon', 'sword', 'aoe', 'chaos', 'fire' },
        vfx = { effectKey = 'vfx_weapon_chaos_cluster', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://10288487412' },
        animation = { animationKey = 'anim_weapon_chaos_cluster', futureAssetHook = 'rbxassetid://TODO_ANIM_WEAPON_CHAOS_CLUSTER' },
    },
    unwing_flyers = {
        id = 'unwing_flyers',
        archetypeId = 'equipment',
        classId = 'knight_sword',
        stage = 'Equipment',
        name = 'Unwing Flyers',
        category = 'Active',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'STR', secondary = 'DEX' },
        tags = { 'equipment', 'weapon', 'sword', 'single_target', 'chaos', 'finisher' },
        vfx = { effectKey = 'vfx_weapon_unwing_flyers', flashinessTier = 3, socket = 'Weapon', futureAssetHook = 'rbxassetid://10288487412' },
        animation = { animationKey = 'anim_weapon_unwing_flyers', futureAssetHook = 'rbxassetid://TODO_ANIM_WEAPON_UNWING_FLYERS' },
    },

    katar_mastery = {
        id = 'katar_mastery',
        archetypeId = 'assassin_path',
        classId = 'assassin',
        stage = 'Base',
        name = 'Katar Mastery',
        category = 'Passive',
        maxLevel = 10,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        tags = { 'passive', 'crit', 'aspd', 'katar' },
        vfx = { effectKey = 'vfx_passive_katar_mastery', flashinessTier = 0, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_KATAR_MASTERY' },
        animation = { animationKey = 'anim_passive', futureAssetHook = 'rbxassetid://TODO_ANIM_PASSIVE' },
    },
    cloaking = {
        id = 'cloaking',
        archetypeId = 'assassin_path',
        classId = 'assassin',
        stage = 'Base',
        name = 'Cloaking',
        category = 'Active',
        maxLevel = 10,
        manaCost = 15,
        cooldownSeconds = 12,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        tags = { 'buff', 'utility', 'self', 'stealth' },
        vfx = { effectKey = 'vfx_assassin_cloaking', flashinessTier = 1, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_ASSASSIN_CLOAKING' },
        animation = { animationKey = 'anim_assassin_cloaking', futureAssetHook = 'rbxassetid://TODO_ANIM_ASSASSIN_CLOAKING' },
    },
    grimtooth = {
        id = 'grimtooth',
        archetypeId = 'assassin_path',
        classId = 'assassin',
        stage = 'Base',
        name = 'Grimtooth',
        category = 'Active',
        maxLevel = 5,
        manaCost = 14,
        cooldownSeconds = 3.5,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        tags = { 'melee', 'physical', 'aoe', 'burst', 'shadow' },
        vfx = { effectKey = 'vfx_assassin_grimtooth', flashinessTier = 2, socket = 'TargetGround', futureAssetHook = 'rbxassetid://TODO_ASSASSIN_GRIMTOOTH' },
        animation = { animationKey = 'anim_assassin_grimtooth', futureAssetHook = 'rbxassetid://TODO_ANIM_ASSASSIN_GRIMTOOTH' },
    },
    sonic_blow = {
        id = 'sonic_blow',
        archetypeId = 'assassin_path',
        classId = 'assassin',
        stage = 'Base',
        name = 'Sonic Blow',
        category = 'Active',
        maxLevel = 10,
        manaCost = 18,
        cooldownSeconds = 6.0,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        prerequisites = {
            { skillId = 'katar_mastery', rank = 3 },
        },
        tags = { 'melee', 'physical', 'single_target', 'multi_hit', 'burst', 'crit' },
        vfx = { effectKey = 'vfx_assassin_sonic_blow', flashinessTier = 3, socket = 'TargetHead', futureAssetHook = 'rbxassetid://TODO_ASSASSIN_SONIC_BLOW' },
        animation = { animationKey = 'anim_assassin_sonic_blow', futureAssetHook = 'rbxassetid://TODO_ANIM_ASSASSIN_SONIC_BLOW' },
    },
    advanced_katar_mastery = {
        id = 'advanced_katar_mastery',
        archetypeId = 'assassin_path',
        classId = 'assassin_cross',
        stage = 'Advanced',
        name = 'Advanced Katar Mastery',
        category = 'Passive',
        maxLevel = 5,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        prerequisites = {
            { skillId = 'katar_mastery', rank = 5 },
        },
        tags = { 'passive', 'crit', 'aspd', 'katar', 'assassin_cross' },
        vfx = { effectKey = 'vfx_passive_advanced_katar_mastery', flashinessTier = 0, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_ADVANCED_KATAR_MASTERY' },
        animation = { animationKey = 'anim_passive', futureAssetHook = 'rbxassetid://TODO_ANIM_PASSIVE' },
    },
    enchant_deadly_poison = {
        id = 'enchant_deadly_poison',
        archetypeId = 'assassin_path',
        classId = 'assassin_cross',
        stage = 'Advanced',
        name = 'Enchant Deadly Poison',
        category = 'Active',
        maxLevel = 5,
        manaCost = 30,
        cooldownSeconds = 30.0,
        statScaling = { primary = 'AGI', secondary = 'LUK' },
        prerequisites = {
            { skillId = 'sonic_blow', rank = 5 },
        },
        tags = { 'buff', 'self', 'poison', 'burst', 'crit', 'assassin_cross' },
        vfx = { effectKey = 'vfx_assassin_enchant_deadly_poison', flashinessTier = 3, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_ASSASSIN_EDP' },
        animation = { animationKey = 'anim_assassin_enchant_deadly_poison', futureAssetHook = 'rbxassetid://TODO_ANIM_ASSASSIN_EDP' },
    },

    fire_bolt = {
        id = 'fire_bolt',
        archetypeId = 'mage_path',
        classId = 'mage',
        stage = 'Base',
        name = 'Fire Bolt',
        category = 'Active',
        maxLevel = 10,
        manaCost = 10,
        cooldownSeconds = 0.5,
        castSeconds = 0.5,
        statScaling = { primary = 'INT', secondary = 'DEX' },
        tags = { 'magic', 'single_target', 'fire', 'multi_hit' },
        vfx = { effectKey = 'vfx_mage_fire_bolt', flashinessTier = 1, socket = 'Hand', futureAssetHook = 'rbxassetid://TODO_FIRE_BOLT' },
        animation = { animationKey = 'anim_mage_fire_bolt', futureAssetHook = 'rbxassetid://TODO_ANIM_FIRE_BOLT' },
    },
    cold_bolt = {
        id = 'cold_bolt',
        archetypeId = 'mage_path',
        classId = 'mage',
        stage = 'Base',
        name = 'Cold Bolt',
        category = 'Active',
        maxLevel = 10,
        manaCost = 10,
        cooldownSeconds = 0.5,
        castSeconds = 0.5,
        statScaling = { primary = 'INT', secondary = 'DEX' },
        tags = { 'magic', 'single_target', 'ice', 'multi_hit' },
        vfx = { effectKey = 'vfx_mage_cold_bolt', flashinessTier = 1, socket = 'Hand', futureAssetHook = 'rbxassetid://TODO_COLD_BOLT' },
        animation = { animationKey = 'anim_mage_cold_bolt', futureAssetHook = 'rbxassetid://TODO_ANIM_COLD_BOLT' },
    },
    soul_strike = {
        id = 'soul_strike',
        archetypeId = 'mage_path',
        classId = 'mage',
        stage = 'Base',
        name = 'Soul Strike',
        category = 'Active',
        maxLevel = 10,
        manaCost = 8,
        cooldownSeconds = 0.6,
        castSeconds = 0.3,
        statScaling = { primary = 'INT', secondary = 'DEX' },
        tags = { 'magic', 'single_target', 'ghost', 'multi_hit' },
        vfx = { effectKey = 'vfx_mage_soul_strike', flashinessTier = 1, socket = 'Hand', futureAssetHook = 'rbxassetid://TODO_SOUL_STRIKE' },
        animation = { animationKey = 'anim_mage_soul_strike', futureAssetHook = 'rbxassetid://TODO_ANIM_SOUL_STRIKE' },
    },
    fire_wall = {
        id = 'fire_wall',
        archetypeId = 'mage_path',
        classId = 'mage',
        stage = 'Base',
        name = 'Fire Wall',
        category = 'Active',
        maxLevel = 10,
        manaCost = 25,
        cooldownSeconds = 2.0,
        castSeconds = 1.0,
        statScaling = { primary = 'INT', secondary = 'DEX' },
        prerequisites = {
            { skillId = 'fire_bolt', rank = 4 },
        },
        tags = { 'magic', 'aoe', 'fire', 'control' },
        vfx = { effectKey = 'vfx_mage_fire_wall', flashinessTier = 2, socket = 'TargetGround', futureAssetHook = 'rbxassetid://TODO_FIRE_WALL' },
        animation = { animationKey = 'anim_mage_fire_wall', futureAssetHook = 'rbxassetid://TODO_ANIM_FIRE_WALL' },
    },

    double_strafe = {
        id = 'double_strafe',
        archetypeId = 'archer_path',
        classId = 'archer',
        stage = 'Base',
        name = 'Double Strafe',
        category = 'Active',
        maxLevel = 10,
        manaCost = 8,
        cooldownSeconds = 0.3,
        statScaling = { primary = 'DEX', secondary = 'AGI' },
        tags = { 'ranged', 'physical', 'single_target', 'multi_hit' },
        vfx = { effectKey = 'vfx_archer_double_strafe', flashinessTier = 1, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_DOUBLE_STRAFE' },
        animation = { animationKey = 'anim_archer_double_strafe', futureAssetHook = 'rbxassetid://TODO_ANIM_DOUBLE_STRAFE' },
    },
    arrow_shower = {
        id = 'arrow_shower',
        archetypeId = 'archer_path',
        classId = 'archer',
        stage = 'Base',
        name = 'Arrow Shower',
        category = 'Active',
        maxLevel = 10,
        manaCost = 12,
        cooldownSeconds = 1.5,
        statScaling = { primary = 'DEX', secondary = 'AGI' },
        prerequisites = {
            { skillId = 'double_strafe', rank = 3 },
        },
        tags = { 'ranged', 'physical', 'aoe' },
        vfx = { effectKey = 'vfx_archer_arrow_shower', flashinessTier = 2, socket = 'TargetGround', futureAssetHook = 'rbxassetid://TODO_ARROW_SHOWER' },
        animation = { animationKey = 'anim_archer_arrow_shower', futureAssetHook = 'rbxassetid://TODO_ANIM_ARROW_SHOWER' },
    },
    improve_concentration = {
        id = 'improve_concentration',
        archetypeId = 'archer_path',
        classId = 'archer',
        stage = 'Base',
        name = 'Improve Concentration',
        category = 'Active',
        maxLevel = 10,
        manaCost = 15,
        cooldownSeconds = 60,
        statScaling = { primary = 'DEX', secondary = 'AGI' },
        prerequisites = {
            { skillId = 'owls_eye', rank = 3 },
        },
        tags = { 'ranged', 'buff', 'self' },
        vfx = { effectKey = 'vfx_archer_improve_concentration', flashinessTier = 1, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_IMPROVE_CONCENTRATION' },
        animation = { animationKey = 'anim_archer_improve_concentration', futureAssetHook = 'rbxassetid://TODO_ANIM_IMPROVE_CONCENTRATION' },
    },
    owls_eye = {
        id = 'owls_eye',
        archetypeId = 'archer_path',
        classId = 'archer',
        stage = 'Base',
        name = "Owl's Eye",
        category = 'Passive',
        maxLevel = 10,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'DEX', secondary = 'LUK' },
        tags = { 'passive', 'accuracy' },
        vfx = { effectKey = 'vfx_passive_owls_eye', flashinessTier = 0, socket = 'Head', futureAssetHook = 'rbxassetid://TODO_OWLS_EYE' },
        animation = { animationKey = 'anim_passive', futureAssetHook = 'rbxassetid://TODO_ANIM_PASSIVE' },
    },
    forward_slash = {
        id = 'forward_slash',
        archetypeId = 'zero_path',
        classId = 'zero',
        stage = 'Base',
        name = 'Rift Drive',
        category = 'Active',
        maxLevel = 10,
        manaCost = 6,
        cooldownSeconds = 0.28,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'melee', 'physical', 'dash', 'afterimage', 'combo', 'zero' },
        vfx = { effectKey = 'vfx_zero_forward_slash', flashinessTier = 2, socket = 'Weapon', futureAssetHook = 'rbxassetid://TODO_ZERO_FORWARD' },
        animation = { animationKey = 'anim_zero_forward_slash', futureAssetHook = 'rbxassetid://TODO_ANIM_ZERO_FORWARD' },
    },
    circular_slash = {
        id = 'circular_slash',
        archetypeId = 'zero_path',
        classId = 'zero',
        stage = 'Base',
        name = 'Falling Halo',
        category = 'Active',
        maxLevel = 10,
        manaCost = 9,
        cooldownSeconds = 0.28,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'melee', 'physical', 'aoe', 'slam', 'afterimage', 'combo', 'zero' },
        vfx = { effectKey = 'vfx_zero_circular_slash', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_ZERO_CIRCULAR' },
        animation = { animationKey = 'anim_zero_circular_slash', futureAssetHook = 'rbxassetid://TODO_ANIM_ZERO_CIRCULAR' },
    },
    evasive_slash = {
        id = 'evasive_slash',
        archetypeId = 'zero_path',
        classId = 'high_zero',
        stage = 'High',
        name = 'Backstep Rend',
        category = 'Active',
        maxLevel = 10,
        manaCost = 10,
        cooldownSeconds = 0.28,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'melee', 'physical', 'dash', 'evasion', 'afterimage', 'combo', 'zero' },
        vfx = { effectKey = 'vfx_zero_evasive_slash', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_ZERO_EVASIVE' },
        animation = { animationKey = 'anim_zero_evasive_slash', futureAssetHook = 'rbxassetid://TODO_ANIM_ZERO_EVASIVE' },
    },
    shadow_clone_slash = {
        id = 'shadow_clone_slash',
        archetypeId = 'zero_path',
        classId = 'transcendent_zero',
        stage = 'Advanced',
        name = 'Twin Eclipse',
        category = 'Active',
        maxLevel = 10,
        manaCost = 20,
        cooldownSeconds = 1.25,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'melee', 'physical', 'multi_hit', 'dash', 'burst', 'afterimage', 'clone', 'auto_target', 'zero' },
        vfx = { effectKey = 'vfx_zero_shadow_clone_slash', flashinessTier = 4, socket = 'TargetHead', futureAssetHook = 'rbxassetid://TODO_ZERO_SHADOW_CLONE' },
        animation = { animationKey = 'anim_zero_shadow_clone_slash', futureAssetHook = 'rbxassetid://TODO_ANIM_ZERO_SHADOW_CLONE' },
    },

    divine_ascent = {
        id = 'divine_ascent',
        archetypeId = 'valkyrie_path',
        classId = 'valkyrie',
        stage = 'Base',
        name = 'Divine Ascent',
        category = 'Active',
        maxLevel = 1,
        manaCost = 0,
        cooldownSeconds = 1.0,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'utility', 'flight', 'toggle', 'mobility', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_divine_ascent', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_ASCENT' },
        animation = { animationKey = 'anim_valkyrie_divine_ascent', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_ASCENT' },
    },
    sky_piercer = {
        id = 'sky_piercer',
        archetypeId = 'valkyrie_path',
        classId = 'valkyrie',
        stage = 'Base',
        name = 'Sky Piercer',
        category = 'Active',
        maxLevel = 10,
        manaCost = 12,
        cooldownSeconds = 1.5,
        statScaling = { primary = 'AGI', secondary = 'STR' },
        tags = { 'melee', 'physical', 'dash', 'flight', 'aoe', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_sky_piercer', flashinessTier = 2, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_SKY_PIERCER' },
        animation = { animationKey = 'anim_valkyrie_sky_piercer', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_SKY_PIERCER' },
    },
    feather_barrage = {
        id = 'feather_barrage',
        archetypeId = 'valkyrie_path',
        classId = 'valkyrie',
        stage = 'Base',
        name = 'Feather Barrage',
        category = 'Active',
        maxLevel = 10,
        manaCost = 15,
        cooldownSeconds = 2.0,
        statScaling = { primary = 'DEX', secondary = 'INT' },
        tags = { 'ranged', 'physical', 'multi_hit', 'flight', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_feather_barrage', flashinessTier = 2, socket = 'Hand', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_FEATHER_BARRAGE' },
        animation = { animationKey = 'anim_valkyrie_feather_barrage', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_FEATHER_BARRAGE' },
    },
    zephyr_veil = {
        id = 'zephyr_veil',
        archetypeId = 'valkyrie_path',
        classId = 'valkyrie',
        stage = 'Base',
        name = 'Zephyr Veil',
        category = 'Active',
        maxLevel = 10,
        manaCost = 20,
        cooldownSeconds = 15.0,
        statScaling = { primary = 'VIT', secondary = 'AGI' },
        tags = { 'buff', 'self', 'defense', 'flight', 'glide', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_zephyr_veil', flashinessTier = 1, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_ZEPHYR_VEIL' },
        animation = { animationKey = 'anim_valkyrie_zephyr_veil', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_ZEPHYR_VEIL' },
    },
    sonic_dive = {
        id = 'sonic_dive',
        archetypeId = 'valkyrie_path',
        classId = 'high_valkyrie',
        stage = 'High',
        name = 'Sonic Dive',
        category = 'Active',
        maxLevel = 10,
        manaCost = 28,
        cooldownSeconds = 4.0,
        statScaling = { primary = 'STR', secondary = 'AGI' },
        prerequisites = {
            { skillId = 'sky_piercer', rank = 5 },
        },
        tags = { 'melee', 'physical', 'aoe', 'flight', 'dive', 'burst', 'destruction', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_sonic_dive', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_SONIC_DIVE' },
        animation = { animationKey = 'anim_valkyrie_sonic_dive', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_SONIC_DIVE' },
    },
    gale_cutter = {
        id = 'gale_cutter',
        archetypeId = 'valkyrie_path',
        classId = 'high_valkyrie',
        stage = 'High',
        name = 'Gale Cutter',
        category = 'Active',
        maxLevel = 10,
        manaCost = 22,
        cooldownSeconds = 3.0,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        prerequisites = {
            { skillId = 'feather_barrage', rank = 3 },
        },
        tags = { 'melee', 'physical', 'multi_hit', 'flight', 'aoe', 'debuff', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_gale_cutter', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_GALE_CUTTER' },
        animation = { animationKey = 'anim_valkyrie_gale_cutter', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_GALE_CUTTER' },
    },
    storm_overdrive = {
        id = 'storm_overdrive',
        archetypeId = 'valkyrie_path',
        classId = 'valkyrie_rebirthed',
        stage = 'Rebirth',
        name = 'Storm Overdrive',
        category = 'Active',
        maxLevel = 10,
        manaCost = 35,
        cooldownSeconds = 30.0,
        statScaling = { primary = 'AGI', secondary = 'INT' },
        prerequisites = {
            { skillId = 'sonic_dive', rank = 3 },
            { skillId = 'gale_cutter', rank = 3 },
        },
        tags = { 'buff', 'self', 'overdrive', 'flight', 'burst', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_storm_overdrive', flashinessTier = 3, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_STORM_OVERDRIVE' },
        animation = { animationKey = 'anim_valkyrie_storm_overdrive', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_STORM_OVERDRIVE' },
    },
    celestial_sovereignty = {
        id = 'celestial_sovereignty',
        archetypeId = 'valkyrie_path',
        classId = 'seraphim',
        stage = 'Advanced',
        name = 'Celestial Sovereignty',
        category = 'Passive',
        maxLevel = 5,
        manaCost = 0,
        cooldownSeconds = 0,
        statScaling = { primary = 'AGI', secondary = 'DEX' },
        tags = { 'passive', 'flight', 'enhancement', 'seraphim', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_celestial_sovereignty', flashinessTier = 0, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_CELESTIAL' },
        animation = { animationKey = 'anim_passive', futureAssetHook = 'rbxassetid://TODO_ANIM_PASSIVE' },
    },
    judgment_descent = {
        id = 'judgment_descent',
        archetypeId = 'valkyrie_path',
        classId = 'seraphim',
        stage = 'Advanced',
        name = 'Judgment Descent',
        category = 'Active',
        maxLevel = 10,
        manaCost = 50,
        cooldownSeconds = 60.0,
        statScaling = { primary = 'STR', secondary = 'AGI' },
        prerequisites = {
            { skillId = 'storm_overdrive', rank = 5 },
            { skillId = 'sonic_dive', rank = 5 },
        },
        tags = { 'melee', 'physical', 'single_target', 'burst', 'flight', 'ultimate', 'cinematic', 'destruction', 'valkyrie' },
        vfx = { effectKey = 'vfx_valkyrie_judgment_descent', flashinessTier = 4, socket = 'Root', futureAssetHook = 'rbxassetid://TODO_VALKYRIE_JUDGMENT' },
        animation = { animationKey = 'anim_valkyrie_judgment_descent', futureAssetHook = 'rbxassetid://TODO_ANIM_VALKYRIE_JUDGMENT' },
    },
}

return SkillDefs
